#library "dropsys"
#include "zcommon.acs"

str Weaps1[12][2]={{"Empty","Nothing"},
		{"AEoDHandGrenade","HandGrenadeDrop"},			// 6019
		{"AEoDStickyMine","StickyMineDrop"},			// 6023
		{"AEoDNecromanticBoneStaff","BoneStaffDrop"},		// 6035
		{"AEoDTNTBunny","TNTBunnyDrop"},			// 6050
		{"AEoDTNT","TNTDrop"},					// 6121
		{"AEoDRemoteDetonator","RemoteDetonatorDrop"},		// 6119
		{"AEoDProxDetonator","ProxDetonatorDrop"},		// 6120
		{"AEoDGlyph","GlyphDrop"},				// 6150
		{"AEoDJackBomb","JackBombDrop"},			// 6151
		{"AEoDPortalGun","PortalGunDrop"},
		{"AEoDLemonNade","LemonNadeDrop"}};	

str Weaps2[11][2]={{"Empty","Nothing"},
		{"AEoDChainsaw","ChainsawDrop"},			// 6065
		{"AEoDKnife","KnifeDrop"},				// 6012
		{"AEoDMedievalAxe","MedievalAxeDrop"},			// 6010
		{"AEoDGauntlets","GauntletsDrop"},			// 6029
		{"AEoDKatana","KatanaDrop"},				// 6047
		{"AEoDPainkiller","PainkillerDrop"},			// 6028
		{"AEoDStroggArmSaw","StroggArmSawDrop"},		// 6031
		{"AEoDVorpalBlade","VorpalBladeDrop"},		// 6152
		{"AEoDScythe","ScytheDrop"},
		{"AEoDSpyKnife","SpyKnifeDrop"}};			

str Weaps3[20][2]={{"Empty","Nothing"},
		{"AEoDShellShocker","ShellShockerDrop"},		// 6125
		{"AEoDDesertEagle","DesertEagleDrop"},			// 6036
		{"AEoDGoldenColts","GoldenColtsDrop"},			// 6037
		{"AEoDMac10","Mac10Drop"},				// 6101
		{"AEoDPistol","PistolDrop"},				// 6067
		{"AEoDSPASShotgun","SPASShotgunDrop"},			// 6068
		{"AEoDMP5","MP5Drop"},					// 6005
		{"AEoDRubinWand","RubinWandDrop"},			// 6003
		{"AEoDTekbow","TekbowDrop"},				// 6043
		{"AEoDFlareGun","FlareGunDrop"},			// 6114
		{"AEoDCrossbow","CrossbowDrop"},			// 6007
		{"AEoDElfWand","ElfWandDrop"},				// 6130
		{"AEoDBeretta","BerettaDrop"},				// 6129
		{"AEoDGargoyleWand","GargoyleWandDrop"},		// 6100
		{"AEoDRifle","RifleDrop"},				// 6099
		{"AEoDBlaster","BlasterDrop"},				// 6097
		{"AEoD357","357Drop"},					// 6098
		{"AEoDAssaultShotgun","AssaultShotgunDrop"},		// 6187
		{"AEoDFiveSevenPistol","FiveSevenPistolDrop"}};		// 6045

str Weaps4[23][2]={{"Empty","Nothing"},
		{"AEoDAWP","AWPDrop"},					// 6194
		{"AEoDCMRifle","CMRifleDrop"},				// 6034
		{"AEoDCombatShotgun","CombatShotgunDrop"},		// 6060
		{"AEoDCrystalGun","CrystalGunDrop"},			// 6039
		{"AEoDDemonOrb","DemonOrbDrop"},			// 6044
		{"AEoDSerpentStaff","SerpentStaffDrop"},		// 6016
		{"AEoDBiorifle","BiorifleDrop"},			// 6040
		{"AEoDDisruptor","DisruptorDrop"},			// 6202
		{"AEoDRiotgun","RiotgunDrop"},				// 6004
		{"AEoDShockRifle","ShockRifleDrop"},			// 6102
		{"AEoDDragonClaw","DragonClawDrop"},			// 6008
		{"AEoDVoodooDoll","VoodooDollDrop"},			// 6091
		{"AEoDBloodShotgun","GunsAkimboDrop"},			// 6186
		{"AEoDBloodShotgun2","GunsAkimboDrop"},			// 6186
		{"AEoDDoubleBarreled","DoubleBarreledDrop"},		// 6188
		{"AEoDSniperRifle","SniperRifleDrop"},			// 6064
		{"AEoDCarbine","CarbineDrop"},				// 6160
		{"AEoDBoltGun","BoltGunDrop"},
		{"AEoDPKShotgun","PKShotgunDrop"},
		{"AEoDGasLauncher","GasLauncherDrop"},
		{"AEoDHeadHunter","HeadHunterDrop"},
		{"AEoDBison","BisonDrop"}};

str Weaps5[17][2]={{"Empty","Nothing"},
		{"AEoDFlamethrower","FlamethrowerDrop"},		// 6078
		{"AEoDFreezethrower","FreezethrowerDrop"},		// 6032
		{"AEoDLasergun","LasergunDrop"},			// 6083
		{"AEoDMinigun","MinigunDrop"},				// 6006
		{"AEoDNailGun","NailGunDrop"},				// 6020
		{"AEoDPlasmaRifle","PlasmaRifleDrop"},			// 6072
		{"AEoDWyvernHeart","WyvernHeartDrop"},			// 6090
		{"AEoDAssaultRifle","AssaultRifleDrop"},		// 6069
		{"AEoDDemonStaff","DemonStaffDrop"},			// 6009
		{"AEoDHyperblaster","HyperblasterDrop"},		// 6052
		{"AEoDNailgunMK2","NailgunMK2Drop"},			// 6103
		{"AEoDSkullRod","SkullRodDrop"},			// 6013
		{"AEoDHornetGun","HornetGunDrop"},			// 6199
		{"AEoDIceStormRod","IceStormRodDrop"},			// 6026
		{"AEoDGaussGun","GaussGunDrop"},			// 6163
		{"AEoDPeaceMaker","PeaceMakerDrop"}};

str Weaps6[16][2]={{"Empty","Nothing"},
		{"AEoDHowitzer","HowitzerDrop"},			// 6117
		{"AEoDChickenLauncher","ChickenLauncherDrop"},		// 6089
		{"AEoDFireStormSpell","FireStormSpellDrop"},		// 6017
		{"AEoDGrenadeLauncher","GrenadeLauncherDrop"},		// 6056
		{"AEoDWarAxe","WarAxeDrop"},				// 6153
		{"AEoDLightningRod","LightningRodDrop"},		// 6018
		{"AEoDMeteoriteRod","MeteoriteRodDrop"},		// 6014
		{"AEoDRazor","RazorDrop"},				// 6080
		{"AEoDRocketLauncher","RocketLauncherDrop"},		// 6061
		{"AEoDScarabStaff","ScarabStaffDrop"},			// 6077
		{"AEoDMissileLauncher","MissileLauncherDrop"},		// 6062
		{"AEoDEnlightenmentStaff","EnlightenmentStaffDrop"},	// 6132
		{"AEoDPMFLayer","PMFLayerDrop"},			// 6189
		{"AEoDScreamer","ScreamerDrop"},
		{"AEoDCowMangler","CowManglerDrop"}};

str Weaps7[21][2]={{"Empty","Nothing"},
		{"AEoDLifeLeech","LifeLeechDrop"},			// 6133
		{"AEoDTeslaCannon","TeslaCannonDrop"},			// 6116
		{"AEoDDevastator","DevastatorDrop"},			// 6042
		{"AEoDPerforator","PerforatorDrop"},			// 6022
		{"AEoDPlutoniumCannon","PlutoniumCannonDrop"},		// 6082
		{"AEoDThunderBolt","ThunderBoltDrop"},			// 6021
		{"AEoDVulcanCannon","VulcanCannonDrop"},		// 6053
		{"AEoDRipperGun","RipperGunDrop"},			// 6038
		{"AEoDPrismaCannon","PrismaCannonDrop"},		// 6104
		{"AEoDPulsegun","PulsegunDrop"},			// 6105
		{"AEoDRaptor","RaptorDrop"},				// 6070
		{"AEoDIncinerator","IncineratorDrop"},			// 6134
		{"AEoDGuardianHead","GuardianHeadDrop"},		// 6135
		{"AEoDIceWand","IceWandDrop"},				// 6076
		{"AEoDArbalest","ArbalestDrop"},			// 6059
		{"AEoDFragLauncher","FragLauncherDrop"},		// 6164
		{"AEoDConcussionLauncher","ConcussionLauncherDrop"},	// 6165
		{"AEoDElectroDriver","ElectroDriverDrop"},
		{"AEoDEidechsenesser","EidechsenesserDrop"},
		{"AEoDHailStorm","HailStormDrop"}};

str Weaps8[24][2]={{"Empty","Nothing"},
		{"AEoDDSparilStaff","DsparilStaffDrop"},		// 6081
		{"AEoDNapalmLauncher","NapalmLauncherDrop"},		// 6192
		{"AEoDHEGrenadeLauncher","HEGrenadeLauncherDrop"},	// 6011
		{"AEoDRailGun","RailGunDrop"},				// 6041
		{"AEoDMindBlower","MindBlowerDrop"},			// 6049
		{"AEoDIncendiary","IncendiaryDrop"},			// 6108
		{"AEoDDeathRay","DeathRayDrop"},			// 6107
		{"AEoDFlakCannon","FlakCannonDrop"},			// 6063
		{"AEoDLichStaff","LichStaffDrop"},			// 6205
		{"AEoDMorserLauncher","MorserLauncherDrop"},		// 6054
		{"AEoDPulseCannon","PulseCannonDrop"},			// 6085
		{"AEoDShredderStaff","ShredderStaffDrop"},		// 6106
		{"AEoDRavenStaff","RavenStaffDrop"},			// 6033
		{"AEoDIonCannon","IonCannonDrop"},			// 6001	
		{"AEoDPhalanx","PhalanxDrop"},				// 6086
		{"AEoDTomeOfSet","TomeOfSetDrop"},			// 6127
		{"AEoDSniperRailgun","SniperRailgunDrop"},		// 6161
		{"AEoDBoneDuster","BoneDusterDrop"},	
		{"AEoDStakeGun","StakeGunDrop"},
		{"AEoDPKSMG","PKSMGDrop"},	
		{"AEoDBoneShotgun","BoneShotgunDrop"},
		{"AEoDGutFlinger","GutFlingerDrop"},
		{"AEoDFlailGun","FlailGunDrop"}};
		
str Weaps9[20][2]={{"Empty","Nothing"},
		{"AEoDSoulReaver","SoulReaverDrop"},			// 6122
		{"AEoDGluonGun","GluonGunDrop"},			// 6123
		{"AEoDTempestStaff","TempestStaffDrop"},		// 6162
		{"AEoDBloodScourge","BloodScourgeDrop2"},		// 6025
		{"AEoDHellCore","HellCoreDrop"},			// 6015
		{"AEoDHERocketLauncher","HERocketLauncherDrop"},	// 6048
		{"AEoDPrototype","PrototypeDrop"},			// 6084
		{"AEoDRailGunPrototype","RailGunPrototypeDrop"},	// 6051
		{"AEoDSoulleech","SoulleechDrop"},			// 6079
		{"AEoDWraithVerge","WraithVergeDrop2"},			// 6027
		{"AEoDCrawler","CrawlerDrop"},				// 6030
		{"AEoDPhotonCannon","PhotonCannonDrop"},		// 6110
		{"AEoDHellRoot","HellRootDrop"},			// 6057
		{"AEoDDrakan","DrakanDrop"},				// 6024
		{"AEoDProteusDynamo","ProteusDynamoDrop"},		// 6109
		{"AEoDHandCannon","HandCannonDrop"},			// 6118
		{"AEoDNecrossbow","NecrossbowDrop"},
		{"AEoDPopcornGun","PopcornGunDrop"},
		{"AEoDBouncer","BouncerDrop"}};

str Weaps0[16][2]={{"Empty","Nothing"},
		{"AEoDVolcanoCannon","VolcanoCannonDrop"},		// 6128
		{"AEoDApocalypse","ApocalypseDrop"},			// 6075
		{"AEoDBFG9000","BFG9000Drop"},				// 6073
		{"AEoDBioForceGun","BioForceGunDrop"},			// 6058
		{"AEoDDarkFlameStaff","DarkFlameStaffDrop"},		// 6087
		{"AEoDNova","NovaDrop"},				// 6074
		{"AEoDQSG","QSGDrop"},					// 6002
		{"AEoDDarkMatterGun","DarkMatterGunDrop"},		// 6088
		{"AEoDFusionCannon","FusionCannonDrop"},		// 6112
		{"AEoDInferno","InfernoDrop"},				// 6111
		{"AEoDRedeemer","RedeemerDrop"},			// 6071
		{"AEoDHellHeavenHand","HellHeavenHandDrop"},		// 6066
		{"AEoDHandOfGod","HandOfGodDrop"},			// 6124
		{"AEoDDeathsHand","DeathsHandDrop"},
		{"AEoDPenetrator","PenetratorDrop"}};			// 6055

int wepidentif=0;
int togglescript=1;
int scriptactivation=0;

script "s797" enter
{
	GiveInventory("MakeVisible",1);	//this line alone was before ENTER script 942. Whatever it does, now it adds it here.
	if(CheckInventory("LimitScriptCheck"))
	{
		if(CheckInventory("LimitScriptActive"))
		{
			togglescript=1;
		}
		else
		{
			togglescript=0;
		}
		terminate;
	}
	else
	{
		togglescript=1;
		GiveInventory("LimitScriptCheck",1);
		GiveInventory("LimitScriptActive",1);
	}
}

script "s798" (int slotmsg)		//slot x full
{
	hudmessage(s:"Slot ",
		   d:slotmsg,
		   s:" full";
	HUDMSG_FADEOUT,100,3,0.5,0.8,2.0,0.5);
}

script "s799" (int wepnumber)		//identifies which weapon(of the arrangement) being is used 
{
	wepidentif=wepnumber;
	
	//And from here, it starts checking if player has a weapon but not it's item, if so, then player got it
	//by cheating. See script 689 at the bottom of this same file
	if (CheckInventory("AEoDHellHeavenHand")==1)
	{
	  if (CheckInventory("HellHeavenHandDrop")!=1)
		scriptactivation=1;
	}
	if (CheckInventory("AEoDNova")==1)
	{
	  if (CheckInventory("NovaDrop")!=1)
		scriptactivation=1;
	}
	if (CheckInventory("AEoDRedeemer")==1)
	{
	  if (CheckInventory("RedeemerDrop")!=1)
		scriptactivation=1;
	}
	if (CheckInventory("AEoDTomeOfSet")==1)
	{
	  if (CheckInventory("TomeOfSetDrop")!=1)
		scriptactivation=1;
	}
	if (CheckInventory("AEoDDarkMatterGun")==1)
	{
	  if (CheckInventory("DarkMatterGunDrop")!=1)
		scriptactivation=1;
	}
	if (CheckInventory("AEoDHandOfGod")==1)
	{
	  if (CheckInventory("HandOfGodDrop")!=1)
		scriptactivation=1;
	}
	if (CheckInventory("AEoDGluonGun")==1)
	{
	  if (CheckInventory("GluonGunDrop")!=1)
		scriptactivation=1;
	}
	if (CheckInventory("AEoDDsparilStaff")==1)
	{
	  if (CheckInventory("DsparilStaffDrop")!=1)
		scriptactivation=1;
	}
	if (CheckInventory("AEoDWarAxe")==1)
	{
	  if (CheckInventory("WarAxeDrop")!=1)
		scriptactivation=1;
	}
	if (CheckInventory("AEoDVulcanCannon")==1)
	{
	  if (CheckInventory("VulcanCannonDrop")!=1)
		scriptactivation=1;
	}


	if (CheckInventory("AEoDShellShocker")==1)
	{
	  if (CheckInventory("ShellShockerDrop")!=1)
		scriptactivation=1;
	}
	if (CheckInventory("AEoDDesertEagle")==1)
	{
	  if (CheckInventory("DesertEagleDrop")!=1)
		scriptactivation=1;
	}
	if (CheckInventory("AEoDAWP")==1)
	{
	  if (CheckInventory("AWPDrop")!=1)
		scriptactivation=1;
	}
	if (CheckInventory("AEoDDisruptor")==1)
	{
	  if (CheckInventory("DisruptorDrop")!=1)
		scriptactivation=1;
	}
	if (CheckInventory("AEoDFlamethrower")==1)
	{
	  if (CheckInventory("FlamethrowerDrop")!=1)
		scriptactivation=1;
	}
	if (CheckInventory("AEoDWyvernHeart")==1)
	{
	  if (CheckInventory("WyvernHeartDrop")!=1)
		scriptactivation=1;
	}
	if (CheckInventory("AEoDTomeOfSet")==1)
	{
	  if (CheckInventory("TomeOfSetDrop")!=1)
		scriptactivation=1;
	}
	if (CheckInventory("AEoDNapalmLauncher")==1)
	{
	  if (CheckInventory("NapalmLauncherDrop")!=1)
		scriptactivation=1;
	}
	if (CheckInventory("AEoDTempestStaff")==1)
	{
	  if (CheckInventory("TempestStaffDrop")!=1)
		scriptactivation=1;
	}
	//ACS_Execute(689,0);
}

// weapon drop scripts

script "s800" (void)		//this one, well, is another part of the dropping script
{
	GiveInventory("WeaponSoundStopper",1);
	if((CheckWeapon("AEoDHandGrenade"))
	|| (CheckWeapon("AEoDStickyMine"))
	|| (CheckWeapon("AEoDNecromanticBoneStaff"))
	|| (CheckWeapon("AEoDTNTBunny"))
	|| (CheckWeapon("AEoDTNT"))
	|| (CheckWeapon("AEoDRemoteDetonator"))
	|| (CheckWeapon("AEoDProxDetonator"))
	|| (CheckWeapon("AEoDGlyph"))
	|| (CheckWeapon("AEoDJackBomb"))
	|| (CheckWeapon("AEoDPortalGun"))
	|| (CheckWeapon("AEoDLemonNade")))
	{
		int weapon1number=wepidentif;
		TakeInventory(Weaps1[weapon1number][0], 1);
		TakeInventory("Weapon1Count",1);
		UseInventory(Weaps1[weapon1number][1]);
		if(CheckInventory("AEoDHandGrenade"))
		{
			SetWeapon("AEoDHandGrenade");
		}
		if(CheckInventory("AEoDStickyMine"))
		{
			SetWeapon("AEoDStickyMine");
		}
		if(CheckInventory("AEoDNecromanticBoneStaff"))
		{
			SetWeapon("AEoDNecromanticBoneStaff");
		}
		if(CheckInventory("AEoDTNTBunny"))
		{
			SetWeapon("AEoDTNTBunny");
		}
		if(CheckInventory("AEoDTNT"))
		{
			SetWeapon("AEoDTNT");
		}
		if(CheckInventory("AEoDRemoteDetonator"))
		{
			SetWeapon("AEoDRemoteDetonator");
		}
		if(CheckInventory("AEoDProxDetonator"))
		{
			SetWeapon("AEoDProxDetonator");
		}
		if(CheckInventory("AEoDGlyph"))
		{
			SetWeapon("AEoDGlyph");
		}
		if(CheckInventory("AEoDJackBomb"))
		{
			SetWeapon("AEoDJackBomb");
		}
		if(CheckInventory("AEoDPortalGun"))
		{
			SetWeapon("AEoDPortalGun");
		}
		if(CheckInventory("AEoDLemonNade"))
		{
			SetWeapon("AEoDLemonNade");
		}
	}
	if(CheckWeapon("AEoDSpellBook"))
	{
		if(CheckInventory("SpellBookChecker")==0)
		{
			UseInventory("RaiseSpellDrop");
		}
		else if(CheckInventory("SpellBookChecker")==1)
		{
			UseInventory("CharmSpellDrop");
		}
		else if(CheckInventory("SpellBookChecker")==2)
		{
			UseInventory("DefileSpellDrop");
		}
		else if(CheckInventory("SpellBookChecker")==3)
		{
			UseInventory("TerrorSpellDrop");
		}
		else if(CheckInventory("SpellBookChecker")==4)
		{
			UseInventory("DrainSpellDrop");
		}
		else if(CheckInventory("SpellBookChecker")==5)
		{
			UseInventory("MorphSpellDrop");
		}
		else if(CheckInventory("SpellBookChecker")==6)
		{
			UseInventory("ChaosSpellDrop");
		}
		else if(CheckInventory("SpellBookChecker")==7)
		{
			UseInventory("SlowSpellDrop");
		}
	}
	if((CheckWeapon("AEoDChainsaw"))
	|| (CheckWeapon("AEoDKnife"))
	|| (CheckWeapon("AEoDMedievalAxe"))
	|| (CheckWeapon("AEoDGauntlets"))
	|| (CheckWeapon("AEoDKatana"))
	|| (CheckWeapon("AEoDPainKiller"))
	|| (CheckWeapon("AEoDStroggArmSaw"))
	|| (CheckWeapon("AEoDVorpalBlade"))
	|| (CheckWeapon("AEoDScythe"))
	|| (CheckWeapon("AEoDSpyKnife")))
	{
		int weapon2number=wepidentif;
		if(CheckWeapon("AEoDMedievalAxe"))
		{
			if(CheckInventory("AEoDAxeCount")==2)
			{
				GiveInventory("AxeDropCheck",1);
				UseInventory("MedievalAxeDrop");
				terminate;
			}
		}
		TakeInventory(Weaps2[weapon2number][0], 1);
		TakeInventory("Weapon2Count",1);
		UseInventory(Weaps2[weapon2number][1]);
		if(CheckInventory("AEoDChainsaw"))
		{
			SetWeapon("AEoDChainsaw");
		}
		if(CheckInventory("AEoDKnife"))
		{
			SetWeapon("AEoDKnife");
		}
		if(CheckInventory("AEoDMedievalAxe"))
		{
			SetWeapon("AEoDMedievalAxe");
		}
		if(CheckInventory("AEoDGauntlets"))
		{
			SetWeapon("AEoDGauntlets");
		}
		if(CheckInventory("AEoDKatana"))
		{
			SetWeapon("AEoDKatana");
		}
		if(CheckInventory("AEoDPainKiller"))
		{
			SetWeapon("AEoDPainKiller");
		}
		if(CheckInventory("AEoDStroggArmSaw"))
		{
			SetWeapon("AEoDStroggArmSaw");
		}
		if(CheckInventory("AEoDVorpalBlade"))
		{
			SetWeapon("AEoDVorpalBlade");
		}	
		if(CheckInventory("AEoDScythe"))
		{
			SetWeapon("AEoDScythe");
		}	
		if(CheckInventory("AEoDSpyKnife"))
		{
			SetWeapon("AEoDSpyKnife");
		}	
	}
	if((CheckWeapon("AEoDShellShocker"))
	|| (CheckWeapon("AEoDDesertEagle"))
	|| (CheckWeapon("AEoDGoldenColts"))
	|| (CheckWeapon("AEoDMac10"))
	|| (CheckWeapon("AEoDPistol"))
	|| (CheckWeapon("AEoDSPASShotgun"))
	|| (CheckWeapon("AEoDMP5"))
	|| (CheckWeapon("AEoDRubinWand"))
	|| (CheckWeapon("AEoDTekbow"))
	|| (CheckWeapon("AEoDFlareGun"))
	|| (CheckWeapon("AEoDCrossbow"))
	|| (CheckWeapon("AEoDElfWand"))
	|| (CheckWeapon("AEoDBeretta"))
	|| (CheckWeapon("AEoDGargoyleWand"))
	|| (CheckWeapon("AEoDRifle"))
	|| (CheckWeapon("AEoDBlaster"))
	|| (CheckWeapon("AEoD357"))
	|| (CheckWeapon("AEoDAssaultShotgun"))
	|| (CheckWeapon("AEoDFiveSevenPistol")))
	{
		int weapon3number=wepidentif;
		if(CheckWeapon("AEoDMac10"))
		{
			if(CheckInventory("AEoDMac10Count")==2)
			{
				GiveInventory("Mac10DropCheck",1);
				UseInventory("Mac10Drop");
				terminate;
			}
		}
		else if(CheckWeapon("AEoDPistol"))
		{
			if(CheckInventory("Doom3PistolCount")==2)
			{
				GiveInventory("PistolDropCheck",1);
				UseInventory("PistolDrop");
				terminate;
			}
		}
		else if(CheckWeapon("AEoDFlareGun"))
		{
			if(CheckInventory("AEoDFlareGunCount")==2)
			{
				GiveInventory("FlareGunDropCheck",1);
				UseInventory("FlareGunDrop");
				terminate;
			}
		}
		else if(CheckWeapon("AEoDBeretta"))
		{
			if(CheckInventory("AEoDBerettaCount")==2)
			{
				GiveInventory("BerettaDropCheck",1);
				UseInventory("BerettaDrop");
				terminate;
			}
		}
		else if(CheckWeapon("AEoDMK32Pistol"))
		{
			if(CheckInventory("AEoDMK32PistolCount")==2)
			{
				GiveInventory("MK32PistolDropCheck",1);
				UseInventory("MK32PistolDrop");
				terminate;
			}
		}
		else if(CheckWeapon("AEoDFiveSevenPistol"))
		{
			if(CheckInventory("AEoDFiveSevenPistolCount")==2)
			{
				GiveInventory("FiveSevenPistolDropCheck",1);
				UseInventory("FiveSevenPistolDrop");
				terminate;
			}
		}
		TakeInventory(Weaps3[weapon3number][0], 1);
		TakeInventory("Weapon3Count",1);
		UseInventory(Weaps3[weapon3number][1]);
		if(CheckInventory("AEoDShellShocker"))
		{
			SetWeapon("AEoDShellShocker");
		}
		if(CheckInventory("AEoDDesertEagle"))
		{
			SetWeapon("AEoDDesertEagle");
		}
		if(CheckInventory("AEoDGoldenColts"))
		{
			SetWeapon("AEoDGoldenColts");
		}
		if(CheckInventory("AEoDMac10"))
		{
			SetWeapon("AEoDMac10");
		}
		if(CheckInventory("AEoDPistol"))
		{
			SetWeapon("AEoDPistol");
		}
		if(CheckInventory("AEoDSPASShotgun"))
		{
			SetWeapon("AEoDSPASShotgun");
		}
		if(CheckInventory("AEoDMP5"))
		{
			SetWeapon("AEoDMP5");
		}
		if(CheckInventory("AEoDRubinWand"))
		{
			SetWeapon("AEoDRubinWand");
		}
		if(CheckInventory("AEoDTekbow"))
		{
			SetWeapon("AEoDTekbow");
		}
		if(CheckInventory("AEoDFlareGun"))
		{
			SetWeapon("AEoDFlareGun");
		}
		if(CheckInventory("AEoDCrossbow"))
		{
			SetWeapon("AEoDCrossbow");
		}
		if(CheckInventory("AEoDElfWand"))
		{
			SetWeapon("AEoDElfWand");
		}
		if(CheckInventory("AEoDBeretta"))
		{
			SetWeapon("AEoDBeretta");
		}
		if(CheckInventory("AEoDGargoyleWand"))
		{
			SetWeapon("AEoDGargoyleWand");
		}
		if(CheckInventory("AEoDRifle"))
		{
			SetWeapon("AEoDRifle");
		}
		if(CheckInventory("AEoDBlaster"))
		{
			SetWeapon("AEoDBlaster");
		}
		if(CheckInventory("AEoD357"))
		{
			SetWeapon("AEoD357");
		}
		if(CheckInventory("AEoDAssaultShotgun"))
		{
			SetWeapon("AEoDAssaultShotgun");
		}
		if(CheckInventory("AEoDFiveSevenPistol"))
		{
			SetWeapon("AEoDFiveSevenPistol");
		}
	}
	if((CheckWeapon("AEoDAWP"))
	|| (CheckWeapon("AEoDCMRifle"))
	|| (CheckWeapon("AEoDCombatShotgun"))
	|| (CheckWeapon("AEoDCrystalGun"))
	|| (CheckWeapon("AEoDDemonOrb"))
	|| (CheckWeapon("AEoDSerpentStaff"))
	|| (CheckWeapon("AEoDBioRifle"))
	|| (CheckWeapon("AEoDDisruptor"))
	|| (CheckWeapon("AEoDRiotGun"))
	|| (CheckWeapon("AEoDShockRifle"))
	|| (CheckWeapon("AEoDDragonClaw"))
	|| (CheckWeapon("AEoDVoodooDoll"))
	|| (CheckWeapon("AEoDBloodShotgun"))
	|| (CheckWeapon("AEoDBloodShotgun2"))
	|| (CheckWeapon("AEoDDoubleBarreled"))
	|| (CheckWeapon("AEoDSniperRifle"))
	|| (CheckWeapon("AEoDCarbine"))
	|| (CheckWeapon("AEoDBoltGun"))
	|| (CheckWeapon("AEoDPKShotgun"))
	|| (CheckWeapon("AEoDGasLauncher"))
	|| (CheckWeapon("AEoDHeadHunter"))
	|| (CheckWeapon("AEoDBison")))
	{
		int weapon4number=wepidentif;
		if(CheckWeapon("AEoDBloodShotgun2"))
		{
			if(CheckInventory("AEoDBloodShotgun2Count"))
			{
				GiveInventory("AEoDBloodShotgun",1);
				UseInventory("GunsAkimboDrop");
				terminate;
			}
		}
		else if(CheckWeapon("AEoDBioRifle"))
		{
			if(CheckInventory("AEoDBiorifleCount")==2)
			{
				GiveInventory("BiorifleDropCheck",1);
				UseInventory("BiorifleDrop");
				terminate;
			}
		}
		else if(CheckWeapon("AEoDShockRifle"))
		{
			if(CheckInventory("AEoDShockRifleCount")==2)
			{
				GiveInventory("ShockRifleDropCheck",1);
				UseInventory("ShockRifleDrop");
				terminate;
			}
		}
		else if(CheckWeapon("AEoDDragonClaw"))
		{
			if(CheckInventory("AEoDDragonClawCount")==2)
			{
				GiveInventory("DragonClawDropCheck",1);
				UseInventory("DragonClawDrop");
				terminate;
			}
		}
		TakeInventory(Weaps4[weapon4number][0], 1);
		TakeInventory("Weapon4Count",1);
		UseInventory(Weaps4[weapon4number][1]);
		if(CheckInventory("AEoDAWP"))
		{
			SetWeapon("AEoDAWP");
		}
		if(CheckInventory("AEoDCMRifle"))
		{
			SetWeapon("AEoDCMRifle");
		}
		if(CheckInventory("AEoDCombatShotgun"))
		{
			SetWeapon("AEoDCombatShotgun");
		}
		if(CheckInventory("AEoDCrystalGun"))
		{
			SetWeapon("AEoDCrystalGun");
		}
		if(CheckInventory("AEoDDemonOrb"))
		{
			SetWeapon("AEoDDemonOrb");
		}
		if(CheckInventory("AEoDSerpentStaff"))
		{
			SetWeapon("AEoDSerpentStaff");
		}
		if(CheckInventory("AEoDBioRifle"))
		{
			SetWeapon("AEoDBioRifle");
		}
		if(CheckInventory("AEoDDisruptor"))
		{
			SetWeapon("AEoDDisruptor");
		}
		if(CheckInventory("AEoDRiotGun"))
		{
			SetWeapon("AEoDRiotGun");
		}
		if(CheckInventory("AEoDShockRifle"))
		{
			SetWeapon("AEoDShockRifle");
		}
		if(CheckInventory("AEoDDragonClaw"))
		{
			SetWeapon("AEoDDragonClaw");
		}
		if(CheckInventory("AEoDVoodooDoll"))
		{
			SetWeapon("AEoDVoodooDoll");
		}
		if(CheckInventory("AEoDBloodShotgun"))
		{
			SetWeapon("AEoDBloodShotgun");
		}
		if(CheckInventory("AEoDBloodShotgun2"))
		{
			SetWeapon("AEoDBloodShotgun2");
		}
		if(CheckInventory("AEoDDoubleBarreled"))
		{
			SetWeapon("AEoDDoubleBarreled");
		}
		if(CheckInventory("AEoDSniperRifle"))
		{
			SetWeapon("AEoDSniperRifle");
		}
		if(CheckInventory("AEoDCarbine"))
		{
			SetWeapon("AEoDCarbine");
		}
		if(CheckInventory("AEoDBoltGun"))
		{
			SetWeapon("AEoDBoltGun");
		}
		if(CheckInventory("AEoDPKShotgun"))
		{
			SetWeapon("AEoDPKShotgun");
		}
		if(CheckInventory("AEoDGasLauncher"))
		{
			SetWeapon("AEoDGasLauncher");
		}		
		if(CheckInventory("AEoDHeadHunter"))
		{
			SetWeapon("AEoDHeadHunter");
		}
		if(CheckInventory("AEoDBison"))
		{
			SetWeapon("AEoDBison");
		}	
	}
	if((CheckWeapon("AEoDFlamethrower"))
	|| (CheckWeapon("AEoDFreezethrower"))
	|| (CheckWeapon("AEoDLasergun"))
	|| (CheckWeapon("AEoDMinigun"))
	|| (CheckWeapon("AEoDNailGun"))
	|| (CheckWeapon("AEoDPlasmaRifle"))
	|| (CheckWeapon("AEoDWyvernHeart"))
	|| (CheckWeapon("AEoDAssaultRifle"))
	|| (CheckWeapon("AEoDDemonStaff"))
	|| (CheckWeapon("AEoDHyperblaster"))
	|| (CheckWeapon("AEoDNailgunMK2"))
	|| (CheckWeapon("AEoDSkullRod"))
	|| (CheckWeapon("AEoDHornetGun"))
	|| (CheckWeapon("AEoDIceStormRod"))
	|| (CheckWeapon("AEoDGaussGun"))
	|| (CheckWeapon("AEoDPeaceMaker")))
	{
		int weapon5number=wepidentif;
		if(CheckWeapon("AEoDHornetGun"))
		{
			if(CheckInventory("AEoDHornetGunCount")==2)
			{
				GiveInventory("HornetGunDropCheck",1);
				UseInventory("HornetGunDrop");
				terminate;
			}
		}
		else if(CheckWeapon("AEoDIceStormRod"))
		{
			if(CheckInventory("AEoDIceStormRodCount")==2)
			{
				GiveInventory("IceStormRodDropCheck",1);
				UseInventory("IceStormRodDrop");
				terminate;
			}
		}
		TakeInventory(Weaps5[weapon5number][0], 1);
		TakeInventory("Weapon5Count",1);
		UseInventory(Weaps5[weapon5number][1]);
		if(CheckInventory("AEoDFlamethrower"))
		{
			SetWeapon("AEoDFlamethrower");
		}
		if(CheckInventory("AEoDFreezethrower"))
		{
			SetWeapon("AEoDFreezethrower");
		}
		if(CheckInventory("AEoDLasergun"))
		{
			SetWeapon("AEoDLasergun");
		}
		if(CheckInventory("AEoDMinigun"))
		{
			SetWeapon("AEoDMinigun");
		}
		if(CheckInventory("AEoDNailGun"))
		{
			SetWeapon("AEoDNailGun");
		}
		if(CheckInventory("AEoDPlasmaRifle"))
		{
			SetWeapon("AEoDPlasmaRifle");
		}
		if(CheckInventory("AEoDWyvernHeart"))
		{
			SetWeapon("AEoDWyvernHeart");
		}
		if(CheckInventory("AEoDAssaultRifle"))
		{
			SetWeapon("AEoDAssaultRifle");
		}
		if(CheckInventory("AEoDDemonStaff"))
		{
			SetWeapon("AEoDDemonStaff");
		}
		if(CheckInventory("AEoDHyperblaster"))
		{
			SetWeapon("AEoDHyperblaster");
		}
		if(CheckInventory("AEoDNailgunMK2"))
		{
			SetWeapon("AEoDNailgunMK2");
		}
		if(CheckInventory("AEoDSkullRod"))
		{
			SetWeapon("AEoDSkullRod");
		}
		if(CheckInventory("AEoDHornetGun"))
		{
			SetWeapon("AEoDHornetGun");
		}
		if(CheckInventory("AEoDIceStormRod"))
		{
			SetWeapon("AEoDIceStormRod");
		}
		if(CheckInventory("AEoDGaussGun"))
		{
			SetWeapon("AEoDGaussGun");
		}
		if(CheckInventory("AEoDPeaceMaker"))
		{
			SetWeapon("AEoDPeaceMaker");
		}
	}
	if((CheckWeapon("AEoDHowitzer"))
	|| (CheckWeapon("AEoDChickenLauncher"))
	|| (CheckWeapon("AEoDFireStormSpell"))
	|| (CheckWeapon("AEoDGrenadeLauncher"))
	|| (CheckWeapon("AEoDWarAxe"))
	|| (CheckWeapon("AEoDLightningRod"))
	|| (CheckWeapon("AEoDMeteoriteRod"))
	|| (CheckWeapon("AEoDRazor"))
	|| (CheckWeapon("AEoDRocketLauncher"))
	|| (CheckWeapon("AEoDScarabStaff"))
	|| (CheckWeapon("AEoDMissileLauncher"))
	|| (CheckWeapon("AEoDEnlightenmentStaff"))
	|| (CheckWeapon("AEoDPMFLayer"))
	|| (CheckWeapon("AEoDScreamer"))
	|| (CheckWeapon("AEoDCowMangler")))
	{
		int weapon6number=wepidentif;
		if(CheckWeapon("AEoDRocketLauncher"))
		{
			if(CheckInventory("AEoDRocketLauncherCount")==2)
			{
				GiveInventory("RocketLauncherDropCheck",1);
				UseInventory("RocketLauncherDrop");
				terminate;
			}
		}
		TakeInventory(Weaps6[weapon6number][0], 1);
		TakeInventory("Weapon6Count",1);
		UseInventory(Weaps6[weapon6number][1]);
		if(CheckInventory("AEoDHowitzer"))
		{
			SetWeapon("AEoDHowitzer");
		}
		if(CheckInventory("AEoDChickenLauncher"))
		{
			SetWeapon("AEoDChickenLauncher");
		}
		if(CheckInventory("AEoDFireStormSpell"))
		{
			SetWeapon("AEoDFireStormSpell");
		}
		if(CheckInventory("AEoDGrenadeLauncher"))
		{
			SetWeapon("AEoDGrenadeLauncher");
		}
		if(CheckInventory("AEoDWarAxe"))
		{
			SetWeapon("AEoDWarAxe");
		}
		if(CheckInventory("AEoDLightningRod"))
		{
			SetWeapon("AEoDLightningRod");
		}
		if(CheckInventory("AEoDMeteoriteRod"))
		{
			SetWeapon("AEoDMeteoriteRod");
		}
		if(CheckInventory("AEoDRazor"))
		{
			SetWeapon("AEoDRazor");
		}
		if(CheckInventory("AEoDRocketLauncher"))
		{
			SetWeapon("AEoDRocketLauncher");
		}
		if(CheckInventory("AEoDScarabStaff"))
		{
			SetWeapon("AEoDScarabStaff");
		}
		if(CheckInventory("AEoDMissileLauncher"))
		{
			SetWeapon("AEoDMissileLauncher");
		}
		if(CheckInventory("AEoDEnlightenmentStaff"))
		{
			SetWeapon("AEoDEnlightenmentStaff");
		}
		if(CheckInventory("AEoDPMFLayer"))
		{
			SetWeapon("AEoDPMFLayer");
		}
		if(CheckInventory("AEoDScreamer"))
		{
			SetWeapon("AEoDScreamer");
		}	
		if(CheckInventory("AEoDCowMangler"))
		{
			SetWeapon("AEoDCowMangler");
		}	
	
	}
	if((CheckWeapon("AEoDLifeLeech"))
	|| (CheckWeapon("AEoDTeslaCannon"))
	|| (CheckWeapon("AEoDDevastator"))
	|| (CheckWeapon("AEoDPerforator"))
	|| (CheckWeapon("AEoDPlutoniumCannon"))
	|| (CheckWeapon("AEoDThunderBolt"))
	|| (CheckWeapon("AEoDVulcanCannon"))
	|| (CheckWeapon("AEoDRipperGun"))
	|| (CheckWeapon("AEoDPrismaCannon"))
	|| (CheckWeapon("AEoDPulsegun"))
	|| (CheckWeapon("AEoDRaptor"))
	|| (CheckWeapon("AEoDIncinerator"))
	|| (CheckWeapon("AEoDGuardianHead"))
	|| (CheckWeapon("AEoDIceWand"))
	|| (CheckWeapon("AEoDArbalest"))
	|| (CheckWeapon("AEoDFragLauncher"))
	|| (CheckWeapon("AEoDConcussionLauncher"))
	|| (CheckWeapon("AEoDElectroDriver"))
	|| (CheckWeapon("AEoDEidechsenesser"))
	|| (CheckWeapon("AEoDHailStorm")))
	{
		int weapon7number=wepidentif;
		if(CheckWeapon("AEoDDevastator"))
		{
			if(CheckInventory("DevastatorCount")==2)
			{
				GiveInventory("DevastatorDropCheck",1);
				UseInventory("DevastatorDrop");
				terminate;
			}
		}
		else if(CheckWeapon("AEoDRaptor"))
		{
			if(CheckInventory("AEoDRaptorCount")==2)
			{
				GiveInventory("RaptorDropCheck",1);
				UseInventory("RaptorDrop");
				terminate;
			}
		}
		else if(CheckWeapon("AEoDTeslaCannon"))
		{
			if(CheckInventory("AEoDTeslaCannonCount")==2)
			{
				GiveInventory("TeslaCannonDropCheck",1);
				UseInventory("TeslaCannonDrop");
				terminate;
			}
		}
		else if(CheckWeapon("AEoDPrismaCannon"))
		{
			if(CheckInventory("AEoDPrismaCannonCount")==2)
			{
				GiveInventory("PrismaCannonDropCheck",1);
				UseInventory("PrismaCannonDrop");
				terminate;
			}
		}
		TakeInventory(Weaps7[weapon7number][0], 1);
		TakeInventory("Weapon7Count",1);
		UseInventory(Weaps7[weapon7number][1]);
		if(CheckInventory("AEoDLifeLeech"))
		{
			SetWeapon("AEoDLifeLeech");
		}
		if(CheckInventory("AEoDTeslaCannon"))
		{
			SetWeapon("AEoDTeslaCannon");
		}
		if(CheckInventory("AEoDDevastator"))
		{
			SetWeapon("AEoDDevastator");
		}
		if(CheckInventory("AEoDPerforator"))
		{
			SetWeapon("AEoDPerforator");
		}
		if(CheckInventory("AEoDPlutoniumCannon"))
		{
			SetWeapon("AEoDPlutoniumCannon");
		}
		if(CheckInventory("AEoDThunderBolt"))
		{
			SetWeapon("AEoDThunderBolt");
		}
		if(CheckInventory("AEoDVulcanCannon"))
		{
			SetWeapon("AEoDVulcanCannon");
		}
		if(CheckInventory("AEoDRipperGun"))
		{
			SetWeapon("AEoDRipperGun");
		}
		if(CheckInventory("AEoDPrismaCannon"))
		{
			SetWeapon("AEoDPrismaCannon");
		}
		if(CheckInventory("AEoDPulsegun"))
		{
			SetWeapon("AEoDPulsegun");
		}
		if(CheckInventory("AEoDRaptor"))
		{
			SetWeapon("AEoDRaptor");
		}
		if(CheckInventory("AEoDIncinerator"))
		{
			SetWeapon("AEoDIncinerator");
		}
		if(CheckInventory("AEoDGuardianHead"))
		{
			SetWeapon("AEoDGuardianHead");
		}
		if(CheckInventory("AEoDIceWand"))
		{
			SetWeapon("AEoDIceWand");
		}
		if(CheckInventory("AEoDArbalest"))
		{
			SetWeapon("AEoDArbalest");
		}
		if(CheckInventory("AEoDFragLauncher"))
		{
			SetWeapon("AEoDFragLauncher");
		}
		if(CheckInventory("AEoDConcussionLauncher"))
		{
			SetWeapon("AEoDConcussionLauncher");
		}
		if(CheckInventory("AEoDElectroDriver"))
		{
			SetWeapon("AEoDElectroDriver");
		}
		if(CheckInventory("AEoDEidechsenesser"))
		{
			SetWeapon("AEoDEidechsenesser");
		}
		if(CheckInventory("AEoDHailStorm"))
		{
			SetWeapon("AEoDHailStorm");
		}
	}
	if((CheckWeapon("AEoDDSparilStaff"))
	|| (CheckWeapon("AEoDNapalmLauncher"))
	|| (CheckWeapon("AEoDHEGrenadeLauncher"))
	|| (CheckWeapon("AEoDRailGun"))
	|| (CheckWeapon("AEoDMindBlower"))
	|| (CheckWeapon("AEoDIncendiary"))
	|| (CheckWeapon("AEoDDeathRay"))
	|| (CheckWeapon("AEoDFlakCannon"))
	|| (CheckWeapon("AEoDLichStaff"))
	|| (CheckWeapon("AEoDMorserLauncher"))
	|| (CheckWeapon("AEoDPulseCannon"))
	|| (CheckWeapon("AEoDShredderStaff"))
	|| (CheckWeapon("AEoDRavenStaff"))
	|| (CheckWeapon("AEoDIonCannon"))
	|| (CheckWeapon("AEoDPhalanx"))
	|| (CheckWeapon("AEoDTomeOfSet"))
	|| (CheckWeapon("AEoDSniperRailgun"))
	|| (CheckWeapon("AEoDBoneDuster"))
	|| (CheckWeapon("AEoDStakeGun"))
	|| (CheckWeapon("AEoDPKSMG"))
	|| (CheckWeapon("AEoDBoneShotgun"))
	|| (CheckWeapon("AEoDGutFlinger"))
	|| (CheckWeapon("AEoDFlailGun")))
	{
		int weapon8number=wepidentif;
		if(CheckWeapon("AEoDRailGun"))
		{
			if(CheckInventory("AEoDRailGunCount")==2)
			{
				GiveInventory("RailGunDropCheck",1);
				UseInventory("RailGunDrop");
				terminate;
			}
		}
		else if(CheckWeapon("AEoDFlakCannon"))
		{
			if(CheckInventory("AEoDFlakCannonCount")==2)
			{
				GiveInventory("FlakCannonDropCheck",1);
				UseInventory("FlakCannonDrop");
				terminate;
			}
		}
		TakeInventory(Weaps8[weapon8number][0], 1);
		TakeInventory("Weapon8Count",1);
		UseInventory(Weaps8[weapon8number][1]);
		if(CheckInventory("AEoDDSparilStaff"))
		{
			SetWeapon("AEoDDSparilStaff");
		}
		if(CheckInventory("AEoDNapalmLauncher"))
		{
			SetWeapon("AEoDNapalmLauncher");
		}
		if(CheckInventory("AEoDHEGrenadeLauncher"))
		{
			SetWeapon("AEoDHEGrenadeLauncher");
		}
		if(CheckInventory("AEoDRailGun"))
		{
			SetWeapon("AEoDRailGun");
		}
		if(CheckInventory("AEoDMindBlower"))
		{
			SetWeapon("AEoDMindBlower");
		}
		if(CheckInventory("AEoDIncendiary"))
		{
			SetWeapon("AEoDIncendiary");
		}
		if(CheckInventory("AEoDDeathRay"))
		{
			SetWeapon("AEoDDeathRay");
		}
		if(CheckInventory("AEoDFlakCannon"))
		{
			SetWeapon("AEoDFlakCannon");
		}
		if(CheckInventory("AEoDLichStaff"))
		{
			SetWeapon("AEoDLichStaff");
		}
		if(CheckInventory("AEoDMorserLauncher"))
		{
			SetWeapon("AEoDMorserLauncher");
		}
		if(CheckInventory("AEoDPulseCannon"))
		{
			SetWeapon("AEoDPulseCannon");
		}
		if(CheckInventory("AEoDShredderStaff"))
		{
			SetWeapon("AEoDShredderStaff");
		}
		if(CheckInventory("AEoDRavenStaff"))
		{
			SetWeapon("AEoDRavenStaff");
		}
		if(CheckInventory("AEoDIonCannon"))
		{
			SetWeapon("AEoDIonCannon");
		}
		if(CheckInventory("AEoDPhalanx"))
		{
			SetWeapon("AEoDPhalanx");
		}
		if(CheckInventory("AEoDTomeOfSet"))
		{
			SetWeapon("AEoDTomeOfSet");
		}
		if(CheckInventory("AEoDSniperRailgun"))
		{
			SetWeapon("AEoDSniperRailgun");
		}
		if(CheckInventory("AEoDBoneDuster"))
		{
			SetWeapon("AEoDBoneDuster");
		}
		if(CheckInventory("AEoDStakeGun"))
		{
			SetWeapon("AEoDStakeGun");
		}
		if(CheckInventory("AEoDPKSMG"))
		{
			SetWeapon("AEoDPKSMG");
		}
		if(CheckInventory("AEoDBoneShotgun"))
		{
			SetWeapon("AEoDBoneShotgun");
		}
		if(CheckInventory("AEoDGutFlinger"))
		{
			SetWeapon("AEoDGutFlinger");
		}		
		if(CheckInventory("AEoDFlailGun"))
		{
			SetWeapon("AEoDFlailGun");
		}	
	}
	if((CheckWeapon("AEoDSoulReaver"))
	|| (CheckWeapon("AEoDGluonGun"))
	|| (CheckWeapon("AEoDTempestStaff"))
	|| (CheckWeapon("AEoDBloodScourge"))
	|| (CheckWeapon("AEoDHellCore"))
	|| (CheckWeapon("AEoDHERocketLauncher"))
	|| (CheckWeapon("AEoDPrototype"))
	|| (CheckWeapon("AEoDRailGunPrototype"))
	|| (CheckWeapon("AEoDSoulleech"))
	|| (CheckWeapon("AEoDWraithVerge"))
	|| (CheckWeapon("AEoDCrawler"))
	|| (CheckWeapon("AEoDPhotonCannon"))
	|| (CheckWeapon("AEoDHellRoot"))
	|| (CheckWeapon("AEoDDrakan"))
	|| (CheckWeapon("AEoDProteusDynamo"))
	|| (CheckWeapon("AEoDHandCannon"))
	|| (CheckWeapon("AEoDNecrossbow"))
	|| (CheckWeapon("AEoDPopcornGun"))
	|| (CheckWeapon("AEoDBouncer")))
	{
		int weapon9number=wepidentif;
		TakeInventory(Weaps9[weapon9number][0], 1);
		TakeInventory("Weapon9Count",1);
		UseInventory(Weaps9[weapon9number][1]);
		if(CheckInventory("AEoDSoulReaver"))
		{
			SetWeapon("AEoDSoulReaver");
		}
		if(CheckInventory("AEoDGluonGun"))
		{
			SetWeapon("AEoDGluonGun");
		}
		if(CheckInventory("AEoDTempestStaff"))
		{
			SetWeapon("AEoDTempestStaff");
		}
		if(CheckInventory("AEoDBloodScourge"))
		{
			SetWeapon("AEoDBloodScourge");
		}
		if(CheckInventory("AEoDHellCore"))
		{
			SetWeapon("AEoDHellCore");
		}
		if(CheckInventory("AEoDHERocketLauncher"))
		{
			SetWeapon("AEoDHERocketLauncher");
		}
		if(CheckInventory("AEoDPrototype"))
		{
			SetWeapon("AEoDPrototype");
		}
		if(CheckInventory("AEoDRailGunPrototype"))
		{
			SetWeapon("AEoDRailGunPrototype");
		}
		if(CheckInventory("AEoDSoulleech"))
		{
			SetWeapon("AEoDSoulleech");
		}
		if(CheckInventory("AEoDWraithVerge"))
		{
			SetWeapon("AEoDWraithVerge");
		}
		if(CheckInventory("AEoDCrawler"))
		{
			SetWeapon("AEoDCrawler");
		}
		if(CheckInventory("AEoDPhotonCannon"))
		{
			SetWeapon("AEoDPhotonCannon");
		}
		if(CheckInventory("AEoDHellRoot"))
		{
			SetWeapon("AEoDHellRoot");
		}
		if(CheckInventory("AEoDDrakan"))
		{
			SetWeapon("AEoDDrakan");
		}
		if(CheckInventory("AEoDProteusDynamo"))
		{
			SetWeapon("AEoDProteusDynamo");
		}
		if(CheckInventory("AEoDHandCannon"))
		{
			SetWeapon("AEoDHandCannon");
		}
		if(CheckInventory("AEoDNecrossbow"))
		{
			SetWeapon("AEoDNecrossbow");
		}
		if(CheckInventory("AEoDPopcornGun"))
		{
			SetWeapon("AEoDPopcornGun");
		}		
		if(CheckInventory("AEoDBouncer"))
		{
			SetWeapon("AEoDBouncer");
		}
	}
	if((CheckWeapon("AEoDVolcanoCannon"))
	|| (CheckWeapon("AEoDApocalypse"))
	|| (CheckWeapon("AEoDBFG9000"))
	|| (CheckWeapon("AEoDBioForceGun"))
	|| (CheckWeapon("AEoDDarkFlameStaff"))
	|| (CheckWeapon("AEoDNova"))
	|| (CheckWeapon("AEoDQSG"))
	|| (CheckWeapon("AEoDDarkMatterGun"))
	|| (CheckWeapon("AEoDFusionCannon"))
	|| (CheckWeapon("AEoDInferno"))
	|| (CheckWeapon("AEoDRedeemer"))
	|| (CheckWeapon("AEoDHellHeavenHand"))
	|| (CheckWeapon("AEoDHandOfGod"))
	|| (CheckWeapon("AEoDDeathsHand"))
	|| (CheckWeapon("AEoDPenetrator")))
	{
		int weapon0number=wepidentif;
		TakeInventory(Weaps0[weapon0number][0], 1);
		TakeInventory("Weapon0Count",1);
		UseInventory(Weaps0[weapon0number][1]);
		if(CheckInventory("AEoDVolcanoCannon"))
		{
			SetWeapon("AEoDVolcanoCannon");
		}
		if(CheckInventory("AEoDApocalypse"))
		{
			SetWeapon("AEoDApocalypse");
		}
		if(CheckInventory("AEoDBFG9000"))
		{
			SetWeapon("AEoDBFG9000");
		}
		if(CheckInventory("AEoDBioForceGun"))
		{
			SetWeapon("AEoDBioForceGun");
		}
		if(CheckInventory("AEoDDarkFlameStaff"))
		{
			SetWeapon("AEoDDarkFlameStaff");
		}
		if(CheckInventory("AEoDNova"))
		{
			SetWeapon("AEoDNova");
		}
		if(CheckInventory("AEoDQSG"))
		{
			SetWeapon("AEoDQSG");
		}
		if(CheckInventory("AEoDDarkMatterGun"))
		{
			SetWeapon("AEoDDarkMatterGun");
		}
		if(CheckInventory("AEoDFusionCannon"))
		{
			SetWeapon("AEoDFusionCannon");
		}
		if(CheckInventory("AEoDInferno"))
		{
			SetWeapon("AEoDInferno");
		}
		if(CheckInventory("AEoDRedeemer"))
		{
			SetWeapon("AEoDRedeemer");
		}
		if(CheckInventory("AEoDHellHeavenHand"))
		{
			SetWeapon("AEoDHellHeavenHand");
		}
		if(CheckInventory("AEoDHandOfGod"))
		{
			SetWeapon("AEoDHandOfGod");
		}
		if(CheckInventory("AEoDDeathsHand"))
		{
			SetWeapon("AEoDDeathsHand");
		}
		if(CheckInventory("AEoDPenetrator"))
		{
			SetWeapon("AEoDPenetrator");
		}
	}
}


script "WeaponSlotToggle" (void)		//the script that changes the Limits to "on" or "off". Activated through a bound key in the menu.
{
	if(togglescript==0)
	{
		PrintBold(s:"weapon slot limits ON");
		GiveInventory("LimitScriptActive",1);
		togglescript=1;
	}
	else if(togglescript==1)
	{
		PrintBold(s:"weapon slot limits OFF");
		TakeInventory("LimitScriptActive",1);
		togglescript=0;
	}
}





script "s689" enter	//this one is the main cheat detector. using the result given by script 799
{			//which changes "scriptactivation" to "1" if player is caught getting a weapon and not it's item.
    int q, active=1;
    while(1)
    {
	if(scriptactivation==1&&GetCVar("AEAntiCheatOff")==0)
	{
		HUDMessage(s:"Cheating makes life easy. Easy life is pink.\nPink you said?";
			HUDMSG_PLAIN,1,10,0.5,0.0,0);
		for(q=0;q<256;q++)
		{
		Light_ChangeToValue(q,255);
		Sector_SetColor(q,255,94,146,10);
		}	
		while(1)
		{
			AmbientSound("HellHeavenHand/UbberThing",127);
			Delay(35*15);
		}
	}
	delay(8);
    }
}

script "s690" (void)		//not even sure...
{
	acs_namedsuspend("s689",0);
}
script "s691" (void)		//not even sure...
{
	acs_namedterminate("s689",0);
}