#library "dropsys"
#include "zcommon.acs"

str Weaps[10][32][5]=

	{	// behold, the first 3d array I encounter in ZDoom! [Ms]
	
		// on the first level, there are 10 weapon slots
		// on the second level, there are 32 possible weapons for each slot
		// on the third level, each weapon is characterized with 4 strings:
		// own name, dropper name, multi-wield counter, multi-wield drop checker
		
		
	
		// slot 1, special stuff
		
		{{"Empty","Nothing",						"Nothing","Nothing"},
		// It's important for the line above to contain the same thing in second
		// ("nothing") that is written everywhere else to signify nothing.
		
		{"AEoDHandgrenade","HandgrenadeDrop",			"Nothing","Nothing","user_AEoDHandgrenade"},	// 6019
		{"AEoDStickyMine","StickyMineDrop",				"Nothing","Nothing","user_AEoDStickyMine"},	// 6023
		{"AEoDBoneStaff","BoneStaffDrop",				"Nothing","Nothing","user_AEoDBoneStaff"},// 6035
		{"AEoDTNTBunny","TNTBunnyDrop",					"Nothing","Nothing","user_AEoDTNTBunny"},	// 6050
		{"AEoDTNT","TNTDrop",							"Nothing","Nothing","user_AEoDTNT"},	// 6121
		{"AEoDRemoteDetonator","RemoteDetonatorDrop",	"Nothing","Nothing","user_AEoDRemoteDetonator"},// 6119
		{"AEoDProxDetonator","ProxDetonatorDrop",		"Nothing","Nothing","user_AEoDProxDetonator"},	// 6120
		{"AEoDGlyph","GlyphDrop",						"Nothing","Nothing","user_AEoDGlyph"},	// 6150
		{"AEoDJackBomb","JackBombDrop",					"Nothing","Nothing","user_AEoDJackBomb"},	// 6151
		{"AEoDPortalGun","PortalGunDrop",				"Nothing","Nothing","user_AEoDPortalGun"},
		{"AEoDLemonNade","LemonNadeDrop",				"Nothing","Nothing","user_AEoDLemonNade"}},
		
		// slot 2, melee weapons
		
		{{"Empty","Nothing",						"Nothing","Nothing"},
		{"AEoDChainsaw","ChainsawDrop",				"Nothing","Nothing","user_AEoDChainsaw"},	// 6065
		{"AEoDKnife","KnifeDrop",					"Nothing","Nothing","user_AEoDKnife"},	// 6012
		{"AEoDMedievalAxe","MedievalAxeDrop",		"AEoDAxeCount","AxeDropCheck","user_AEoDMedievalAxe"},// 6010
		{"AEoDGauntlets","GauntletsDrop",			"Nothing","Nothing","user_AEoDGauntlets"},	// 6029
		{"AEoDKatana","KatanaDrop",					"Nothing","Nothing","user_AEoDKatana"},	// 6047
		{"AEoDPainkiller","PainkillerDrop",			"Nothing","Nothing","user_AEoDPainkiller"},	// 6028
		{"AEoDStroggArmSaw","StroggArmSawDrop",		"Nothing","Nothing","user_AEoDStroggArmSaw"},	// 6031
		{"AEoDVorpalBlade","VorpalBladeDrop",		"Nothing","Nothing","user_AEoDVorpalBlade"},	// 6152
		{"AEoDScythe","ScytheDrop",					"Nothing","Nothing","user_AEoDScythe"},
		{"AEoDSpyKnife","SpyKnifeDrop",				"Nothing","Nothing","user_AEoDSpyKnife"}},
		
		// slot 3, low-tier weapons
		
		{{"Empty","Nothing",								"Nothing","Nothing"},
		{"AEoDShellShocker","ShellShockerDrop",				"Nothing","Nothing","user_AEoDShellShocker"},	// 6125
		{"AEoDDesertEagle","DesertEagleDrop",				"Nothing","Nothing","user_AEoDDesertEagle"},	// 6036
		{"AEoDGoldenColts","GoldenColtsDrop",				"Nothing","Nothing","user_AEoDGoldenColts"},	// 6037
		{"AEoDMac10","Mac10Drop","AEoDMac10Count",			"Mac10DropCheck","user_AEoDMac10"},		// 6101
		{"AEoDSPASShotgun","SPASShotgunDrop",				"Nothing","Nothing","user_AEoDSPASShotgun"},	// 6068
		{"AEoDMP5","MP5Drop",								"Nothing","Nothing","user_AEoDMP5"},	// 6005
		{"AEoDTekbow","TekbowDrop",							"Nothing","Nothing","user_AEoDTekbow"},	// 6043
		{"AEoDFlaregun","FlareGunDrop","AEoDFlareGunCount",	"FlareGunDropCheck","user_AEoDFlaregun"},//6114
		{"AEoDCrossbow","CrossbowDrop",						"Nothing","Nothing","user_AEoDCrossbow"},	// 6007
		{"AEoDBeretta","BerettaDrop",						"AEoDBerettaCount","BerettaDropCheck","user_AEoDBeretta"},// 6129
		{"AEoDGargoyleWand","GargoyleWandDrop",				"Nothing","Nothing","user_AEoDGargoyleWand"},	// 6100
		{"AEoDBlaster","BlasterDrop",						"Nothing","Nothing","user_AEoDBlaster"},	// 6097
		{"AEoDAssaultShotgun","AssaultShotgunDrop",			"Nothing","Nothing","user_AEoDAssaultShotgun"},		// 6187
		},
		
		// slot 4, low-to-mid-tier weapons

		{{"Empty","Nothing",						"Nothing","Nothing"},
		{"AEoDAWP","AWPDrop",						"Nothing","Nothing","user_AEoDAWP"},	// 6194
		{"AEoDCMRifle","CMRifleDrop",				"Nothing","Nothing","user_AEoDCMRifle"},	// 6034
		{"AEoDCombatShotgun","CombatShotgunDrop",	"Nothing","Nothing","user_AEoDCombatShotgun"},	// 6060
		{"AEoDCrystalGun","CrystalGunDrop",			"Nothing","Nothing","user_AEoDCrystalGun"},	// 6039
		{"AEoDDemonOrb","DemonOrbDrop",				"Nothing","Nothing","user_AEoDDemonOrb"},	// 6044
		{"AEoDSerpentStaff","SerpentStaffDrop",		"Nothing","Nothing","user_AEoDSerpentStaff"},	// 6016
		{"AEoDBioRifle","BiorifleDrop",				"AEoDBiorifleCount","BiorifleDropCheck","user_AEoDBioRifle"},// 6040
		{"AEoDDisruptor","DisruptorDrop",			"Nothing","Nothing","user_AEoDDisruptor"},	// 6202
		{"AEoDRiotgun","RiotgunDrop",				"Nothing","Nothing","user_AEoDRiotgun"},	// 6004
		{"AEoDShockRifle","ShockRifleDrop",			"AEoDShockRifleCount","ShockRifleDropCheck","user_AEoDShockRifle"},// 6102
		{"AEoDDragonClaw","DragonClawDrop",			"AEoDDragonClawCount","DragonClawDropCheck","user_AEoDDragonClaw"},// 6008
		{"AEoDVoodooDoll","VoodooDollDrop",			"Nothing","Nothing","user_AEoDVoodooDoll"},	// 6091
		{"AEoDBloodShotgun","BloodShotgunDrop",		"AEoDBloodShotgunCount","BloodShotgunDropCheck","user_AEoDBloodShotgun"},	// 6186
		{"AEoDCarbine","CarbineDrop",				"Nothing","Nothing","user_AEoDCarbine"},	// 6160
		{"AEoDBoltGun","BoltGunDrop",				"Nothing","Nothing","user_AEoDBoltGun"},
		{"AEoDPKShotgun","PKShotgunDrop",			"Nothing","Nothing","user_AEoDPKShotgun"},
		{"AEoDGasLauncher","GasLauncherDrop",		"Nothing","Nothing","user_AEoDGasLauncher"},
		{"AEoDHeadHunter","HeadHunterDrop",			"Nothing","Nothing","user_AEoDHeadHunter"},
		{"AEoDBison","BisonDrop",					"Nothing","Nothing","user_AEoDBison"},
		{"AEoDC14","C14Drop",						"Nothing","Nothing","user_AEoDC14"}},

		// slot 5, rapid fire weapons

		{{"Empty","Nothing",						"Nothing","Nothing"},
		{"AEoDFlamethrower","FlamethrowerDrop",		"Nothing","Nothing","user_AEoDFlamethrower"},	// 6078
		{"AEoDFreezethrower","FreezethrowerDrop",	"Nothing","Nothing","user_AEoDFreezethrower"},	// 6032
		{"AEoDLasergun","LasergunDrop",				"Nothing","Nothing","user_AEoDLasergun"},	// 6083
		{"AEoDMinigun","MinigunDrop",				"Nothing","Nothing","user_AEoDMinigun"},	// 6006
		{"AEoDNailGun","NailGunDrop",				"Nothing","Nothing","user_AEoDNailGun"},	// 6020
		{"AEoDPlasmaRifle","PlasmaRifleDrop",		"Nothing","Nothing","user_AEoDPlasmaRifle"},	// 6072
		{"AEoDWyvernHeart","WyvernHeartDrop",		"Nothing","Nothing","user_AEoDWyvernHeart"},	// 6090
		{"AEoDDemonStaff","DemonStaffDrop",			"Nothing","Nothing","user_AEoDDemonStaff"},	// 6009
		{"AEoDHyperBlaster","HyperblasterDrop",		"Nothing","Nothing","user_AEoDHyperBlaster"},	// 6052
		{"AEoDNailgunMK2","NailgunMK2Drop",			"Nothing","Nothing","user_AEoDNailgunMK2"},	// 6103
		{"AEoDSkullRod","SkullRodDrop",				"Nothing","Nothing","user_AEoDSkullRod"},	// 6013
		{"AEoDHornetGun","HornetGunDrop",			"AEoDHornetGunCount","HornetGunDropCheck","user_AEoDHornetGun"},// 6199
		{"AEoDIceStormRod","IceStormRodDrop",		"AEoDIceStormRodCount","IceStormRodDropCheck","user_AEoDIceStormRod"},// 6026
		{"AEoDGaussGun","GaussGunDrop",				"Nothing","Nothing","user_AEoDGaussGun"},	// 6163
		{"AEoDFusionChaingun","FusionChaingunDrop",	"Nothing","Nothing","user_AEoDFusionChaingun"},
		{"AEoDPeaceMaker","PeaceMakerDrop",			"Nothing","Nothing","user_AEoDPeaceMaker"}},

		// slot 6, explosives

		{{"Empty","Nothing",							"Nothing","Nothing"},
		{"AEoDHowitzer","HowitzerDrop",					"Nothing","Nothing","user_AEoDHowitzer"},	// 6117
		{"AEoDChickenLauncher","ChickenLauncherDrop",	"Nothing","Nothing","user_AEoDChickenLauncher"},	// 6089
		{"AEoDFireStormSpell","FireStormSpellDrop",		"Nothing","Nothing","user_AEoDFireStormSpell"},	// 6017
		{"AEoDGrenadeLauncher","GrenadeLauncherDrop",	"Nothing","Nothing","user_AEoDGrenadeLauncher"},	// 6056
		{"AEoDWarAxe","WarAxeDrop",						"Nothing","Nothing","user_AEoDWarAxe"},	// 6153
		{"AEoDLightningRod","LightningRodDrop",			"Nothing","Nothing","user_AEoDLightningRod"},	// 6018
		{"AEoDMeteoriteRod","MeteoriteRodDrop",			"Nothing","Nothing","user_AEoDMeteoriteRod"},	// 6014
		{"AEoDRazor","RazorDrop",						"Nothing","Nothing","user_AEoDRazor"},	// 6080
		{"AEoDRocketLauncher","RocketLauncherDrop",		"AEoDRocketLauncherCount","RocketLauncherDropCheck","user_AEoDRocketLauncher"},		// 6061
		{"AEoDScarabStaff","ScarabStaffDrop",			"Nothing","Nothing","user_AEoDScarabStaff"},	// 6077
		{"AEoDMissileLauncher","MissileLauncherDrop",	"Nothing","Nothing","user_AEoDMissileLauncher"},	// 6062
		{"AEoDPMFLayer","PMFLayerDrop",					"Nothing","Nothing","user_AEoDPMFLayer"},	// 6189
		{"AEoDScreamer","ScreamerDrop",					"Nothing","Nothing","user_AEoDScreamer"},
		{"AEoDCowMangler","CowManglerDrop",				"Nothing","Nothing","user_AEoDCowMangler"},
		{"AEoDEnlightenmentStaff","EnlightenmentStaffDrop","Nothing","Nothing","user_AEoDEnlightenmentStaff"}	// 6132
		},

		// slot 7, mid-to-high-tier weapons

		{{"Empty","Nothing",							"Nothing","Nothing"},
		{"AEoDLifeLeech","LifeLeechDrop",				"Nothing","Nothing","user_AEoDLifeLeech"},	// 6133
		{"AEoDTeslaCannon","TeslaCannonDrop",			"AEoDTeslaCannonCount","TeslaCannonDropCheck","user_AEoDTeslaCannon"},// 6116
		{"AEoDDevastator","DevastatorDrop",				"DevastatorCount","DevastatorDropCheck","user_AEoDDevastator"},// 6042
		{"AEoDPerforator","PerforatorDrop",				"Nothing","Nothing","user_AEoDPerforator"},	// 6022
		{"AEoDPlutoniumCannon","PlutoniumCannonDrop",	"Nothing","Nothing","user_AEoDPlutoniumCannon"},	// 6082
		{"AEoDThunderBolt","ThunderBoltDrop",			"Nothing","Nothing","user_AEoDThunderBolt"},	// 6021
		{"AEoDVulcanCannon","VulcanCannonDrop",			"Nothing","Nothing","user_AEoDVulcanCannon"},	// 6053
		{"AEoDRipperGun","RipperGunDrop",				"Nothing","Nothing","user_AEoDRipperGun"},	// 6038
		{"AEoDPrismaCannon","PrismaCannonDrop",			"AEoDPrismaCannonCount","PrismaCannonDropCheck","user_AEoDPrismaCannon"},// 6104
		{"AEoDPulsegun","PulsegunDrop",					"Nothing","Nothing","user_AEoDPulsegun"},	// 6105
		{"AEoDRaptor","RaptorDrop","AEoDRaptorCount",	"RaptorDropCheck","user_AEoDRaptor"},	// 6070
		{"AEoDIncinerator","IncineratorDrop",			"Nothing","Nothing","user_AEoDIncinerator"},	// 6134
		{"AEoDGuardianHead","GuardianHeadDrop",			"Nothing","Nothing","user_AEoDGuardianHead"},	// 6135
		{"AEoDIceWand","IceWandDrop",					"Nothing","Nothing","user_AEoDIceWand"},	// 6076
		{"AEoDArbalest","ArbalestDrop",					"Nothing","Nothing","user_AEoDArbalest"},	// 6059
		{"AEoDFragLauncher","FragLauncherDrop",			"Nothing","Nothing","user_AEoDFragLauncher"},	// 6164
		{"AEoDConcussionLauncher","ConcussionLauncherDrop","Nothing","Nothing","user_AEoDConcussionLauncher"},// 6165
		{"AEoDElectroDriver","ElectroDriverDrop",		"Nothing","Nothing","user_AEoDElectroDriver"},
		{"AEoDEidechsenesser","EidechsenesserDrop",		"Nothing","Nothing","user_AEoDEidechsenesser"},
		{"AEoDHailstorm","HailstormDrop",				"Nothing","Nothing","user_AEoDHailstorm"},
		{"AEoDSuperShotgun","SuperShotgunDrop",			"AEoDSuperShotgunCount","SuperShotgunDropCheck","user_AEoDSuperShotgun"}},

		// slot 8, high-tier weapons

		{{"Empty",					"Nothing",				"Nothing","Nothing"},
		{"AEoDDSparilStaff",		"DsparilStaffDrop",		"Nothing","Nothing","user_AEoDDSparilStaff"},	// 6081
		{"AEoDNapalmLauncher",		"NapalmLauncherDrop",	"Nothing","Nothing","user_AEoDNapalmLauncher"},	// 6192
		{"AEoDHEGrenadeLauncher",	"HEGrenadeLauncherDrop","Nothing","Nothing","user_AEoDHEGrenadeLauncher"},// 6011
		{"AEoDRailGun",				"RailGunDrop",			"Nothing","Nothing","user_AEoDRailGun"},// 6041
		{"AEoDMindBlower",			"MindBlowerDrop",		"Nothing","Nothing","user_AEoDMindBlower"},	// 6049
		{"AEoDIncendiary",			"IncendiaryDrop",		"Nothing","Nothing","user_AEoDIncendiary"},	// 6108
		{"AEoDDeathRay",			"DeathRayDrop",			"Nothing","Nothing","user_AEoDDeathRay"},	// 6107
		{"AEoDFlakCannon",			"FlakCannonDrop",		"AEoDFlakCannonCount",	"FlakCannonDropCheck","user_AEoDFlakCannon"},// 6063
		{"AEoDLichStaff",			"LichStaffDrop",		"Nothing","Nothing","user_AEoDLichStaff"},	// 6205
		{"AEoDMorserLauncher",		"MorserLauncherDrop",	"Nothing","Nothing","user_AEoDMorserLauncher"},	// 6054
		{"AEoDPulseCannon",			"PulseCannonDrop",		"Nothing","Nothing","user_AEoDPulseCannon"},	// 6085
		{"AEoDShredderStaff",		"ShredderStaffDrop",	"Nothing","Nothing","user_AEoDShredderStaff"},	// 6106
		{"AEoDRavenStaff",			"RavenStaffDrop",		"Nothing","Nothing","user_AEoDRavenStaff"},	// 6033
		{"AEoDIonCannon",			"IonCannonDrop",		"Nothing","Nothing","user_AEoDIonCannon"},	// 6001	
		{"AEoDPhalanx",				"PhalanxDrop",			"Nothing","Nothing","user_AEoDPhalanx"},	// 6086
		{"AEoDTomeOfSet",			"TomeOfSetDrop",		"Nothing","Nothing","user_AEoDTomeOfSet"},	// 6127
		{"AEoDSniperRailgun",		"SniperRailgunDrop",	"Nothing","Nothing","user_AEoDSniperRailgun"},	// 6161
		{"AEoDBoneDuster",			"BoneDusterDrop",		"Nothing","Nothing","user_AEoDBoneDuster"},	
		{"AEoDStakeGun",			"StakeGunDrop",			"Nothing","Nothing","user_AEoDStakeGun"},
		{"AEoDPKSMG",				"PKSMGDrop",			"Nothing","Nothing","user_AEoDPKSMG"},	
		{"AEoDBoneShotgun",			"BoneShotgunDrop",		"Nothing","Nothing","user_AEoDBoneShotgun"},
		{"AEoDGutFlinger",			"GutFlingerDrop",		"Nothing","Nothing","user_AEoDGutFlinger"},
		{"AEoDFlailGun",			"FlailGunDrop",			"Nothing","Nothing","user_AEoDFlailGun"}},

		// slot 9, very-high-tier weapons

		{{"Empty",					"Nothing",				"Nothing","Nothing"},
		{"AEoDSoulReaver",			"SoulReaverDrop",		"Nothing","Nothing","user_AEoDSoulReaver"},	// 6122
		{"AEoDGluonGun",			"GluonGunDrop",			"Nothing","Nothing","user_AEoDGluonGun"},	// 6123
		{"AEoDTempestStaff",		"TempestStaffDrop",		"Nothing","Nothing","user_AEoDTempestStaff"},	// 6162
		{"AEoDBloodScourge",		"BloodScourgeDrop2",	"Nothing","Nothing","user_AEoDBloodScourge"},	// 6025
		{"AEoDHellCore",			"HellCoreDrop",			"Nothing","Nothing","user_AEoDHellCore"},	// 6015
		{"AEoDHERocketLauncher",	"HERocketLauncherDrop",	"Nothing","Nothing","user_AEoDHERocketLauncher"},// 6048
		{"AEoDPrototype",			"PrototypeDrop",		"Nothing","Nothing","user_AEoDPrototype"},	// 6084
		{"AEoDRailGunPrototype",	"RailGunPrototypeDrop",	"Nothing","Nothing","user_AEoDRailGunPrototype"},// 6051
		{"AEoDSoulleech",			"SoulleechDrop",		"Nothing","Nothing","user_AEoDSoulleech"},	// 6079
		{"AEoDWraithVerge",			"WraithVergeDrop2",		"Nothing","Nothing","user_AEoDWraithVerge"},	// 6027
		{"AEoDCrawler",				"CrawlerDrop",			"Nothing","Nothing","user_AEoDCrawler"},	// 6030
		{"AEoDPhotonCannon",		"PhotonCannonDrop",		"Nothing","Nothing","user_AEoDPhotonCannon"},	// 6110
		{"AEoDHellRoot",			"HellRootDrop",			"Nothing","Nothing","user_AEoDHellRoot"},	// 6057
		{"AEoDDrakan",				"DrakanDrop",			"Nothing","Nothing","user_AEoDDrakan"},	// 6024
		{"AEoDProteusDynamo",		"ProteusDynamoDrop",	"Nothing","Nothing","user_AEoDProteusDynamo"},	// 6109
		{"AEoDHandCannon",			"HandCannonDrop",		"Nothing","Nothing","user_AEoDHandCannon"},	// 6118
		{"AEoDNecrossbow",			"NecrossbowDrop",		"Nothing","Nothing","user_AEoDNecrossbow"},
		{"AEoDPopcornGun",			"PopcornGunDrop",		"Nothing","Nothing","user_AEoDPopcornGun"},
		{"AEoDBouncer",				"BouncerDrop",			"Nothing","Nothing","user_AEoDBouncer"}},

		// slot 0, super weapons

		{{"Empty",				"Nothing",				"Nothing","Nothing", "Nothing"},
		{"AEoDVolcanoCannon",	"VolcanoCannonDrop",	"Nothing","Nothing", "user_AEoDVolcanoCannon"},	// 6128
		{"AEoDApocalypse",		"ApocalypseDrop",		"Nothing","Nothing", "user_AEoDApocalypse"},	// 6075
		{"AEoDBFG9000",			"BFG9000Drop",			"Nothing","Nothing", "user_AEoDBFG9000"},	// 6073
		//{"AEoDBioForceGun",		"BioForceGunDrop",		"Nothing","Nothing", "user_AEoDBioForceGun"},	// 6058
		{"AEoDDarkFlameStaff",	"DarkFlameStaffDrop",	"Nothing","Nothing", "user_AEoDDarkFlameStaff"},	// 6087
		{"AEoDNova",			"NovaDrop",				"Nothing","Nothing", "user_AEoDNova"},	// 6074
		{"AEoDQSG",				"QSGDrop",				"Nothing","Nothing", "user_AEoDQSG"},	// 6002
		{"AEoDDarkMatterGun",	"DarkMatterGunDrop",	"Nothing","Nothing", "user_AEoDDarkMatterGun"},	// 6088
		{"AEoDFusionCannon",	"FusionCannonDrop",		"Nothing","Nothing", "user_AEoDFusionCannon"},	// 6112
		{"AEoDInferno",			"InfernoDrop",			"Nothing","Nothing", "user_AEoDInferno"},	// 6111
		{"AEoDRedeemer",		"RedeemerDrop",			"Nothing","Nothing", "user_AEoDRedeemer"},	// 6071
		{"AEoDHellHeavenHand",	"HellHeavenHandDrop",	"Nothing","Nothing", "user_AEoDHellHeavenHand"},	// 6066
		{"AEoDHandOfGod",		"HandOfGodDrop",		"Nothing","Nothing", "user_AEoDHandOfGod"},	// 6124
		{"AEoDDeathsHand",		"DeathsHandDrop",		"Nothing","Nothing", "user_AEoDDeathsHand"},
		{"AEoDPenetrator",		"PenetratorDrop",		"Nothing","Nothing", "user_AEoDPenetrator"},	// 6055
		{"AEoDSoulReaper",		"SoulReaperDrop",		"Nothing","Nothing", "user_AEoDSoulReaper"}}
	};
	
//int wepidentif=0;	// this variable is never used
int togglescript=1;
int scriptactivation=0;

script "s797" enter
{
	int plrnum = PlayerNumber();
	if(!(GetUserCvar(plrnum,"user_WeaponSlotLimits")))
	{
		TakeInventory("LimitScriptCheck",1000);
		TakeInventory("LimitScriptActive",1000);
	}
	else
	{
		GiveInventory("LimitScriptCheck",1);
		GiveInventory("LimitScriptActive",1);
	}
}

str PrettyNames[256] = {
/*  0-  7*/	"(unusable)","Hand Grenade","Sticky Mine","Glyph","Proximity Detonator","Remote Detonator","TNT","Jackbomb",
/*  8- 15*/	"Necromantic Bone Staff","Portal Gun","Combustible Lemons","Knife","Medieval Axe","Gauntlets","Katana","Vorpal Blade",
/* 16- 23*/	"Unholy Scythe","Strogg Arm Saw","Chainsaw","Painkiller","Spy Knife","Beretta","Blaster","Gargoyle Wand",
/* 24- 31*/	"MP5","Assault Shotgun","Golden Colts","SPAS Shotgun","Magic Crossbow","Tekbow","Desert Eagle","Mac-10",
/* 32- 39*/	"Flare Gun","Shell Shocker","Serpent Staff","Riotgun","Disruptor","Demon Orb","Carbine Rifle","Combat Shotgun",
/* 40- 47*/	"Crystal Gun","Voodoo Doll","Blood Shotgun","GES Biorifle","Dragon Claw","Boltgun","Shock Rifle","Painkiller Shotgun",
/* 48- 55*/	"Combat Manual Rifle","Gas Rocket Launcher","Righteous Bison","Head Hunter Sniper Rifle","AWP Sniper Rifle","Ice Storm Rod","Lasergun","Nailgun",
/* 56- 63*/	"Demon Staff","Gauss Gun","Nailgun MK2","Hornet Gun","Wyvern Heart","Plasma Rifle","Flamethrower","Freezethrower",
/* 64- 71*/	"Skull Rod","Hyperblaster","Minigun","Peacemaker","Mini Missile Launcher","Fire Storm Spell","PMF Mine Layer","Lightning Rod",
/* 72- 79*/	"Meteorite Rod","Razor Launcher","Grenade Launcher","Rocket Launcher","Scarab Staff","Chicken Launcher","Howitzer","Screamer Revolver",
/* 80- 87*/	"Cow Mangler","War Axe","Enlightenment Staff","Pulse Gun","Eidechsenesser","Incinerator","Thunderbolt","Perforator",
/* 88- 95*/	"Prisma Cannon","Electrodriver","Ice Wand","Devastator","Guardian Head","Frag Grenade Launcher","Ripper Gun","Life Leech",
/* 96-103*/	"Wormwood Arbalest","Concussion Missile Launcher","Plutonium Cannon","Raptor Chaingun","Tesla Cannon","Hailstorm Chaingun","Vulcan Cannon","Bone Shotgun",
/*104-111*/	"Painkiller Machinegun","Stake Gun","Pulse Cannon","Raven Staff","Ion Cannon","Railgun","HE Grenade Launcher","Tome of Set",
/*112-119*/	"Phalanx","Sniper Railgun","Napalm Launcher","Lich Staff","Death Ray","Mind Blower","Flak Cannon","D'sparil Staff",
/*120-127*/	"Gut Flinger","Mortar Launcher","Experimental Incendiary Launcher","Flail Gun","Bone Duster","Shredder Staff","Soul Leech","Wraithverge",
/*128-135*/	"Proteus Dynamo","Railgun Prototype","HE Rocket Launcher","Hellcore","Tempest Staff","Photon Cannon","Crawler","Multi-Mode Prototype",
/*136-143*/	"Soul Reaver","Gluon Gun","Bloodscourge","Popcorn Gun","Hellroot","Drakan Sword","Bouncer Launcher","Necrossbow",
/*144-151*/	"Hand Cannon","Bio Force Gun","BFG 9000","Dark Matter Gun","Redeemer","Fusion Cannon","Quantum Singularity Generator","Penetrator",
/*152-159*/	"Nova","Apocalypse","Volcano Cannon","Dark Flame Staff","Inferno Syphon","Death's Hand","Soul Reaper","Hand of God",
/*160-164*/	"Hell and Heaven Hand!!!","TNT Bunny","Fusion Chaingun","C-14 \"Impaler\" Gauss Rifle", "Super Double Barreled Shotgun"
}; 
// Whenever you should, just append new weapons to the end of this list. Never delete from it, replace with "(unused)" instead.

script "s798" (int slotmsg, int prettyname)		//slot x full
{
	hudmessage(s:"Slot ",
		   d:slotmsg,
		   s:" full";
	HUDMSG_FADEOUT,100,3,0.5,0.8,2.0,0.5);
	if(prettyname > 0 && prettyname < 256)
		hudmessage(s:"Can't pick up \ck",s:PrettyNames[prettyname];HUDMSG_FADEOUT,101,3,0.5,0.83,2.0,0.5);
	else
		hudmessage(s:"Can't pick some not configured yet weapon up";HUDMSG_FADEOUT,101,3,0.5,0.83,2.0,0.5);
}

script "idfuckall" (void) // props to Major Cooke for the name
{
	for(int i=0; i<10; i++) for(int j=0; j<32; j++)
	{
		hudmessage(s:"C H E A T E R ' S   P A R A D I S E ! ! !";HUDMSG_FADEOUT,101,2,0.5,0.77,2.0,0.5);
		SpawnProjectile(0, StrParam(s:Weaps[i][j][0],s:"Item"), 
			random(0, 255), random(1,random(2,500)), random(1,random(2,500)), 1, 0);
		SpawnProjectile(0, StrParam(s:Weaps[i][j][0],s:"NoAmmo"), 
			random(0, 255), random(1,random(2,500)), random(1,random(2,500)), 1, 0);
		Delay(random(0,random(0,1)));
	}
}

script "s799" (int wepnumber)		//identifies which weapon(of the arrangement) being is used 
{
	/*
	wepidentif=wepnumber;	// this number is never used
	
	//And from here, it starts checking if player has a weapon but not it's item, if so, then player got it
	//by cheating. See script 689 at the bottom of this same file
	
	for(int slot=0; slot<=9; slot++)	// cycling through weapon slots
		for(int wep=1; wep<32; wep++)	// cycling through weapons of each slot
			if (CheckInventory(Weaps[slot][wep][0]))	// if has weapon
				if (!CheckInventory(Weaps[slot][wep][1])) // but not the drop
				{
					scriptactivation=1;		// prepare your ears
					ACS_NamedExecute("s689",0,0,0,0);
					slot=10;wep=33;	// cycles end
				}
	*/
	Terminate;		
	// Does nothing instead.
	// Anti-cheat system is disabled for now.
}

// weapon drop scripts

script "s800" (void)		//this one, well, is another part of the dropping script
{
	GiveInventory("WeaponSoundStopper",1);
	
	for(int slot=0; slot<=9; slot++)	// cycling through weapon slots
		for(int wep=1; wep<32; wep++)	// cycling through weapons of each slot
			if(CheckWeapon(Weaps[slot][wep][0]))	// if player's holding it--
			{
				if(Weaps[slot][wep][2] != Weaps[0][0][1] &&	// if the akimbo counter isn't "nothing"
				   CheckInventory(Weaps[slot][wep][2]) > 1) // AND if you have more than one...
						GiveInventory(Weaps[slot][wep][3],1); // give akimbo-drop-checker
				else	// if that multi-wieldable was the last one, OR
				{		// if the akimbo counter is "nothing" (weapon isn't dual-wieldable)
					TakeInventory(Weaps[slot][wep][0], 1);	// take weapon
					TakeInventory(strparam(s:"Weapon", d:(slot+1)%10 ,s:"Count"),1);	// take token
				}
				GiveInventory(Weaps[slot][wep][1],1); 	// get dropper
				UseInventory(Weaps[slot][wep][1]);		// use dropper
				slot=10;wep=33;	// go away
			}
}


script "WeaponSlotToggle" (void) net	//the script that changes the Limits to "on" or "off". Activated through a bound key in the menu.
{
	int plrnum = PlayerNumber();
	if(!(GetUserCvar(plrnum,"user_WeaponSlotLimits")))
	{
		PrintBold(s:"weapon slot limits ON");
		SetUserCvar(plrnum,"user_WeaponSlotLimits",1);
		GiveInventory("LimitScriptActive",1);
	}
	else
	{
		PrintBold(s:"weapon slot limits OFF");
		SetUserCvar(plrnum,"user_WeaponSlotLimits",0);
		TakeInventory("LimitScriptActive",1000);
	}
}

Script "WeaponSlotLimitCheck" (int class) net //Checks to see if a weapon can be added to slot.
{
	int plrnum = PlayerNumber();
	str wepcnt = StrParam(s:"Weapon",i:class,s:"Count");
	str mx = StrParam(s:"user_MaxWeapons",i:class);
	if (GetUserCvar(plrnum,"user_WeaponSlotLimits") == 1)
	{
		if (!CheckInventory("LimitScriptActive"))
			GiveInventory("LimitScriptActive",1);
		
		if (CheckInventory(wepcnt) >= GetUserCvar(plrnum,mx))
			{	SetResultValue(0);	Terminate;	}
		
		SetResultValue(1);
		Terminate;
	}
	else
	{
		//PrintBold(s:"Weapon Slots Off");
		TakeInventory("LimitScriptActive",1000);
		SetResultValue(1);
	}
}


//==============================================================================
//	Weapon Slot Customization
//	Developed by Major Cooke
//==============================================================================

Script "SelectAEoDWeapon" (int class) net
{
	Log(s:"Deprecated. Please rebind key to the 'slot' command.");
	Terminate;
	/*
	if (CheckInventory("MorphOverrideable"))
	{
		TakeInventory("WeaponModeToken",1000);
		GiveInventory("WeaponModeToken",class);
		GiveInventory("HudSwapper",1);
		Terminate;
	}

	if ((GetActorProperty(0,APROP_Dormant)) || (GetActorProperty(0,APROP_HEALTH) <= 0)
		|| CheckInventory("cammin") > 0 || (GetWeapon() == "AEoDDemonMorphHand"))	Terminate;
		
	int c = class % 10;
	str wc = StrParam(s:"Weapon",d:c,s:"Count");
	if(!CheckInventory(wc)) Terminate;
	
	str aew = StrParam(s:"user_AEWeaps",d:class);
	int slotmax = GetCvar(aew); //Get the current maximum number of weapons available in that category.
		
	int curslot = class - 1; //Goes from 1 to 10, not 0 to 9. And yet, the giant array at the top did not take that into account...
	

	str weapOrder[32];
	bool slotSwitched = false;
	bool rep = false;
	int plrnum = PlayerNumber();	
	int prevslot = GetUserCvar(plrnum,"user_previousSlot");
	int currentindex = GetUserCvar(plrnum,"user_currentid");
	int holdnumber;
	int wep;
	int t;

	//The hold number is what weapon we're currently on by ID. 
	//Check first to see if we're on the same slot.
	//If not, reset the current ID and index back to the start.
	if (class != prevslot)
	{
		slotSwitched = true;
		SetUserCvar(plrnum,"user_previousSlot",class);
		SetUserCvar(plrnum,"user_currentid",1);
		currentindex = 1;
		holdnumber = 0;
	}
	
	
	
	int index = 1;
	
	// [MS]The better way to do this is by sorting ids by indices.
	// If using quick sort, time complexity can be O((n log n)+n).
	// This is space for improvement in future.
	
	// [MC] I have no idea what you're talking about, Michaelis. :P
	
	// Prepare index-ordered weapons list (quadratic complexity)
	while(index <= slotmax)
	{
		int found = 0;
		for(t = 1; t <= slotmax; t++)
		{
			if(GetUserCvar(plrnum,Weaps[curslot][t][4]) == index)
			{
				weapOrder[index] = Weaps[curslot][t][0];
				++found; ++index;
			}
		}
		if(!found)
		{
			//[MC] OI. What happened to my conflict detections here!?
			Print(s:"Missing weapon priority detected!\nChange this in the config options.\nMissing priority: ", d:index, s:" / ", d:slotmax, s:"\nIn Slot: ", d:class);
			Terminate;
		}
	}
	
	str curWeap = GetWeapon();
	//Get index of current weapon
	for(holdnumber = 1; 
		stricmp(curWeap, weapOrder[holdnumber]) && (holdnumber<slotmax); 
		++holdnumber);
	if(holdnumber==slotmax) holdnumber=0;	// holding weapon at the END of the slot, go back to the start.

	//Push the selector forward. If the selector's beyond slotmax, loop
	//sets it back right in the beginning.
	currentindex = holdnumber + 1;
	
	int ticker = 0;		//Check for conflicts.
	
	while(currentindex != holdnumber && ticker++ < slotmax) 
	{
		if (currentindex > slotmax) currentindex = 1;
		
		//log(s:"ticker ",d:ticker,s:"      currentindex = ",d:currentindex,s:" / ",d:slotmax,s:"   holdnumber = ",d:holdnumber);
		if (SetWeapon(weapOrder[currentindex])) break;
			
		currentindex++;
	}
	//log(s:"Exiting, currentindex = ",d:currentindex,s:" / ",d:slotmax,s:"   holdnumber = ",d:holdnumber);
	
	//log(s:"Looks like something went over a loop.\n");
	*/
}

Script "RecordWeapon" (void)
{
	int plr = PlayerNumber();
	str weap = GetWeapon();
	
	if (!stricmp(weap,"") || !stricmp(weap,"AEoDDemonMorphHand"))
	{
		SetUserCvar(plr, "AEoD_PreMorphWeapon", "");
	}
	SetUserCvar(plr, "AEoD_PreMorphWeapon", weap);
	if (GetCvar("aeodweapondebug"))
		Log(s: GetUserCvar(plr,"AEoD_PreMorphWeapon"), s: "\n");
}

Script "PostMorphWeapon" ENTER
{
	int plr = PlayerNumber();
	str weap = GetUserCvar(plr,"AEoD_PreMorphWeapon");
	
	if (!stricmp(weap,"") || !stricmp(weap,"AEoDDemonMorphHand"))
	{
		if (GetCvar("aeodweapondebug"))
			Log(s: weap, s: "\n");
		SetWeapon(weap);
	}
}

