#library "hammer"
#include "zcommon.acs"

int hammerweapon=0;

script "s957" (void)
{
	if(CheckWeapon("AEoDHandGrenade"))
	{
		hammerweapon=101;
	}
	else if(CheckWeapon("AEoDStickyMine"))
	{
		hammerweapon=102;
	}
	else if(CheckWeapon("AEoDNecromanticBoneStaff"))
	{
		hammerweapon=103;
	}
	else if(CheckWeapon("AEoDTNTBunny"))
	{
		hammerweapon=104;
	}
	else if(CheckWeapon("AEoDTNT"))
	{
		hammerweapon=105;
	}
	else if(CheckWeapon("AEoDRemoteDetonator"))
	{
		hammerweapon=106;
	}
	else if(CheckWeapon("AEoDProxDetonator"))
	{
		hammerweapon=107;
	}
	else if(CheckWeapon("AEoDGlyph"))
	{
		hammerweapon=108;
	}
	else if(CheckWeapon("AEoDJackBomb"))
	{
		hammerweapon=109;
	}
	else if(CheckWeapon("AEoDSpellBook"))
	{
		hammerweapon=110;
	}
	if(CheckWeapon("AEoDChainsaw"))
	{
		hammerweapon=201;
	}
	else if(CheckWeapon("AEoDKnife"))
	{
		hammerweapon=202;
	}
	else if(CheckWeapon("AEoDMedievalAxe"))
	{
		hammerweapon=203;
	}
	else if(CheckWeapon("AEoDGauntlets"))
	{
		hammerweapon=204;
	}
	else if(CheckWeapon("AEoDKatana"))
	{
		hammerweapon=205;
	}
	else if(CheckWeapon("AEoDPainKiller"))
	{
		hammerweapon=206;
	}
	else if(CheckWeapon("AEoDStroggArmSaw"))
	{
		hammerweapon=207;
	}
	else if(CheckWeapon("AEoDVorpalBlade"))
	{
		hammerweapon=208;
	}
	if(CheckWeapon("AEoDShellShocker"))
	{
		hammerweapon=301;
	}
	else if(CheckWeapon("AEoDDesertEagle"))
	{
		hammerweapon=302;
	}
	else if(CheckWeapon("AEoDGoldenColts"))
	{
		hammerweapon=303;
	}
	else if(CheckWeapon("AEoDMac10"))
	{
		hammerweapon=304;
	}
	else if(CheckWeapon("AEoDPistol"))
	{
		hammerweapon=305;
	}
	else if(CheckWeapon("AEoDSPASShotgun"))
	{
		hammerweapon=306;
	}
	else if(CheckWeapon("AEoDMP5"))
	{
		hammerweapon=307;
	}
	else if(CheckWeapon("AEoDRubinWand"))
	{
		hammerweapon=308;
	}
	else if(CheckWeapon("AEoDTekbow"))
	{
		hammerweapon=309;
	}
	else if(CheckWeapon("AEoDFlareGun"))
	{
		hammerweapon=310;
	}
	else if(CheckWeapon("AEoDCrossbow"))
	{
		hammerweapon=311;
	}
	else if(CheckWeapon("AEoDElfWand"))
	{
		hammerweapon=312;
	}
	else if(CheckWeapon("AEoDBeretta"))
	{
		hammerweapon=313;
	}
	else if(CheckWeapon("AEoDGargoyleWand"))
	{
		hammerweapon=314;
	}
	else if(CheckWeapon("AEoDRifle"))
	{
		hammerweapon=315;
	}
	else if(CheckWeapon("AEoDBlaster"))
	{
		hammerweapon=316;
	}
	else if(CheckWeapon("AEoD357"))
	{
		hammerweapon=317;
	}
	else if(CheckWeapon("AEoDAssaultShotgun"))
	{
		hammerweapon=318;
	}
	else if(CheckWeapon("AEoDFiveSevenPistol"))
	{
		hammerweapon=319;
	}
	if(CheckWeapon("AEoDAWP"))
	{
		hammerweapon=401;
	}
	else if(CheckWeapon("AEoDCMRifle"))
	{
		hammerweapon=402;
	}
	else if(CheckWeapon("AEoDCombatShotgun"))
	{
		hammerweapon=403;
	}
	else if(CheckWeapon("AEoDCrystalGun"))
	{
		hammerweapon=404;
	}
	else if(CheckWeapon("AEoDDemonOrb"))
	{
		hammerweapon=405;
	}
	else if(CheckWeapon("AEoDSerpentStaff"))
	{
		hammerweapon=406;
	}
	else if(CheckWeapon("AEoDBioRifle"))
	{
		hammerweapon=407;
	}
	else if(CheckWeapon("AEoDDisruptor"))
	{
		hammerweapon=408;
	}
	else if(CheckWeapon("AEoDRiotGun"))
	{
		hammerweapon=409;
	}
	else if(CheckWeapon("AEoDShockRifle"))
	{
		hammerweapon=410;
	}
	else if(CheckWeapon("AEoDDragonClaw"))
	{
		hammerweapon=411;
	}
	else if(CheckWeapon("AEoDVoodooDoll"))
	{
		hammerweapon=412;
	}
	else if(CheckWeapon("AEoDBloodShotgun"))
	{
		hammerweapon=413;
	}
	else if(CheckWeapon("AEoDBloodShotgun2"))
	{
		hammerweapon=414;
	}
	else if(CheckWeapon("AEoDDoubleBarreled"))
	{
		hammerweapon=415;
	}
	else if(CheckWeapon("AEoDSniperRifle"))
	{
		hammerweapon=416;
	}
	else if(CheckWeapon("AEoDCarbine"))
	{
		hammerweapon=417;
	}
	if(CheckWeapon("AEoDFlamethrower"))
	{
		hammerweapon=501;
	}
	else if(CheckWeapon("AEoDFreezethrower"))
	{
		hammerweapon=502;
	}
	else if(CheckWeapon("AEoDLasergun"))
	{
		hammerweapon=503;
	}
	else if(CheckWeapon("AEoDMinigun"))
	{
		hammerweapon=504;
	}
	else if(CheckWeapon("AEoDNailGun"))
	{
		hammerweapon=505;
	}
	else if(CheckWeapon("AEoDPlasmaRifle"))
	{
		hammerweapon=506;
	}
	else if(CheckWeapon("AEoDWyvernHeart"))
	{
		hammerweapon=507;
	}
	else if(CheckWeapon("AEoDDemonStaff"))
	{
		hammerweapon=509;
	}
	else if(CheckWeapon("AEoDHyperblaster"))
	{
		hammerweapon=510;
	}
	else if(CheckWeapon("AEoDNailgunMK2"))
	{
		hammerweapon=511;
	}
	else if(CheckWeapon("AEoDSkullRod"))
	{
		hammerweapon=512;
	}
	else if(CheckWeapon("AEoDHornetGun"))
	{
		hammerweapon=513;
	}
	else if(CheckWeapon("AEoDIceStormRod"))
	{
		hammerweapon=514;
	}
	else if(CheckWeapon("AEoDGaussGun"))
	{
		hammerweapon=515;
	}
	if(CheckWeapon("AEoDHowitzer"))
	{
		hammerweapon=601;
	}
	else if(CheckWeapon("AEoDChickenLauncher"))
	{
		hammerweapon=602;
	}
	else if(CheckWeapon("AEoDFireStormSpell"))
	{
		hammerweapon=603;
	}
	else if(CheckWeapon("AEoDGrenadeLauncher"))
	{
		hammerweapon=604;
	}
	else if(CheckWeapon("AEoDWarAxe"))
	{
		hammerweapon=605;
	}
	else if(CheckWeapon("AEoDLightningRod"))
	{
		hammerweapon=606;
	}
	else if(CheckWeapon("AEoDMeteoriteRod"))
	{
		hammerweapon=607;
	}
	else if(CheckWeapon("AEoDRazor"))
	{
		hammerweapon=608;
	}
	else if(CheckWeapon("AEoDRocketLauncher"))
	{
		hammerweapon=609;
	}
	else if(CheckWeapon("AEoDScarabStaff"))
	{
		hammerweapon=610;
	}
	else if(CheckWeapon("AEoDMissileLauncher"))
	{
		hammerweapon=611;
	}
	else if(CheckWeapon("AEoDEnlightenmentStaff"))
	{
		hammerweapon=612;
	}
	else if(CheckWeapon("AEoDPMFLayer"))
	{
		hammerweapon=613;
	}
	if(CheckWeapon("AEoDLifeLeech"))
	{
		hammerweapon=701;
	}
	else if(CheckWeapon("AEoDTeslaCannon"))
	{
		hammerweapon=702;
	}
	else if(CheckWeapon("AEoDDevastator"))
	{
		hammerweapon=703;
	}
	else if(CheckWeapon("AEoDPerforator"))
	{
		hammerweapon=704;
	}
	else if(CheckWeapon("AEoDPlutoniumCannon"))
	{
		hammerweapon=705;
	}
	else if(CheckWeapon("AEoDThunderBolt"))
	{
		hammerweapon=706;
	}
	else if(CheckWeapon("AEoDVulcanCannon"))
	{
		hammerweapon=707;
	}
	else if(CheckWeapon("AEoDRipperGun"))
	{
		hammerweapon=708;
	}
	else if(CheckWeapon("AEoDPrismaCannon"))
	{
		hammerweapon=709;
	}
	else if(CheckWeapon("AEoDPulsegun"))
	{
		hammerweapon=710;
	}
	else if(CheckWeapon("AEoDRaptor"))
	{
		hammerweapon=711;
	}
	else if(CheckWeapon("AEoDIncinerator"))
	{
		hammerweapon=712;
	}
	else if(CheckWeapon("AEoDGuardianHead"))
	{
		hammerweapon=713;
	}
	else if(CheckWeapon("AEoDIceWand"))
	{
		hammerweapon=714;
	}
	else if(CheckWeapon("AEoDArbalest"))
	{
		hammerweapon=715;
	}
	else if(CheckWeapon("AEoDFragLauncher"))
	{
		hammerweapon=716;
	}
	else if(CheckWeapon("AEoDConcussionLauncher"))
	{
		hammerweapon=717;
	}
	if(CheckWeapon("AEoDDSparilStaff"))
	{
		hammerweapon=801;
	}
	else if(CheckWeapon("AEoDNapalmLauncher"))
	{
		hammerweapon=802;
	}
	else if(CheckWeapon("AEoDHEGrenadeLauncher"))
	{
		hammerweapon=803;
	}
	else if(CheckWeapon("AEoDRailGun"))
	{
		hammerweapon=804;
	}
	else if(CheckWeapon("AEoDMindBlower"))
	{
		hammerweapon=805;
	}
	else if(CheckWeapon("AEoDIncendiary"))
	{
		hammerweapon=806;
	}
	else if(CheckWeapon("AEoDDeathRay"))
	{
		hammerweapon=807;
	}
	else if(CheckWeapon("AEoDFlakCannon"))
	{
		hammerweapon=808;
	}
	else if(CheckWeapon("AEoDLichStaff"))
	{
		hammerweapon=809;
	}
	else if(CheckWeapon("AEoDMorserLauncher"))
	{
		hammerweapon=810;
	}
	else if(CheckWeapon("AEoDPulseCannon"))
	{
		hammerweapon=811;
	}
	else if(CheckWeapon("AEoDShredderStaff"))
	{
		hammerweapon=812;
	}
	else if(CheckWeapon("AEoDRavenStaff"))
	{
		hammerweapon=813;
	}
	else if(CheckWeapon("AEoDIonCannon"))
	{
		hammerweapon=814;
	}
	else if(CheckWeapon("AEoDPhalanx"))
	{
		hammerweapon=815;
	}
	else if(CheckWeapon("AEoDTomeOfSet"))
	{
		hammerweapon=816;
	}
	else if(CheckWeapon("AEoDSniperRailgun"))
	{
		hammerweapon=817;
	}
	if(CheckWeapon("AEoDSoulReaver"))
	{
		hammerweapon=901;
	}
	else if(CheckWeapon("AEoDGluonGun"))
	{
		hammerweapon=902;
	}
	else if(CheckWeapon("AEoDTempestStaff"))
	{
		hammerweapon=903;
	}
	else if(CheckWeapon("AEoDBloodScourge"))
	{
		hammerweapon=904;
	}
	else if(CheckWeapon("AEoDHellCore"))
	{
		hammerweapon=905;
	}
	else if(CheckWeapon("AEoDHERocketLauncher"))
	{
		hammerweapon=906;
	}
	else if(CheckWeapon("AEoDPrototype"))
	{
		hammerweapon=907;
	}
	else if(CheckWeapon("AEoDRailGunPrototype"))
	{
		hammerweapon=908;
	}
	else if(CheckWeapon("AEoDSoulleech"))
	{
		hammerweapon=909;
	}
	else if(CheckWeapon("AEoDWraithVerge"))
	{
		hammerweapon=910;
	}
	else if(CheckWeapon("AEoDCrawler"))
	{
		hammerweapon=911;
	}
	else if(CheckWeapon("AEoDPhotonCannon"))
	{
		hammerweapon=912;
	}
	else if(CheckWeapon("AEoDHellRoot"))
	{
		hammerweapon=913;
	}
	else if(CheckWeapon("AEoDDrakan"))
	{
		hammerweapon=914;
	}
	else if(CheckWeapon("AEoDProteusDynamo"))
	{
		hammerweapon=915;
	}
	else if(CheckWeapon("AEoDHandCannon"))
	{
		hammerweapon=916;
	}
	if(CheckWeapon("AEoDVolcanoCannon"))
	{
		hammerweapon=1001;
	}
	else if(CheckWeapon("AEoDApocalypse"))
	{
		hammerweapon=1002;
	}
	else if(CheckWeapon("AEoDBFG9000"))
	{
		hammerweapon=1003;
	}
	else if(CheckWeapon("AEoDBioForceGun"))
	{
		hammerweapon=1004;
	}
	else if(CheckWeapon("AEoDDarkFlameStaff"))
	{
		hammerweapon=1005;
	}
	else if(CheckWeapon("AEoDNova"))
	{
		hammerweapon=1006;
	}
	else if(CheckWeapon("AEoDQSG"))
	{
		hammerweapon=1007;
	}
	else if(CheckWeapon("AEoDDarkMatterGun"))
	{
		hammerweapon=1008;
	}
	else if(CheckWeapon("AEoDFusionCannon"))
	{
		hammerweapon=1009;
	}
	else if(CheckWeapon("AEoDInferno"))
	{
		hammerweapon=1010;
	}
	else if(CheckWeapon("AEoDRedeemer"))
	{
		hammerweapon=1011;
	}
	else if(CheckWeapon("AEoDHellHeavenHand"))
	{
		hammerweapon=1012;
	}
	else if(CheckWeapon("AEoDHandOfGod"))
	{
		hammerweapon=1013;
	}
	else if(CheckWeapon("AEoDDeathsHand"))
	{
		hammerweapon=1014;
	}
}

script 958 (void)
{
	if(hammerweapon==101)
	{
		SetWeapon("AEoDHandGrenade");
	}
	else if(hammerweapon==102)
	{
		SetWeapon("AEoDStickyMine");
	}
	else if(hammerweapon==103)
	{
		SetWeapon("AEoDNecromanticBoneStaff");
	}
	else if(hammerweapon==104)
	{
		SetWeapon("AEoDTNTBunny");
	}
	else if(hammerweapon==105)
	{
		SetWeapon("AEoDTNT");
	}
	else if(hammerweapon==106)
	{
		SetWeapon("AEoDRemoteDetonator");
	}
	else if(hammerweapon==107)
	{
		SetWeapon("AEoDProxDetonator");
	}
	else if(hammerweapon==108)
	{
		SetWeapon("AEoDGlyph");
	}
	else if(hammerweapon==109)
	{
		SetWeapon("AEoDJackBomb");
	}
	else if(hammerweapon==110)
	{
		SetWeapon("AEoDSpellBook");
	}
	if(hammerweapon==201)
	{
		SetWeapon("AEoDChainsaw");
	}
	else if(hammerweapon==202)
	{
		SetWeapon("AEoDKnife");
	}
	else if(hammerweapon==203)
	{
		SetWeapon("AEoDMedievalAxe");
	}
	else if(hammerweapon==204)
	{
		SetWeapon("AEoDGauntlets");
	}
	else if(hammerweapon==205)
	{
		SetWeapon("AEoDKatana");
	}
	else if(hammerweapon==206)
	{
		SetWeapon("AEoDPainKiller");
	}
	else if(hammerweapon==207)
	{
		SetWeapon("AEoDStroggArmSaw");
	}
	else if(hammerweapon==208)
	{
		SetWeapon("AEoDVorpalBlade");
	}
	if(hammerweapon==301)
	{
		SetWeapon("AEoDShellShocker");
	}
	else if(hammerweapon==302)
	{
		SetWeapon("AEoDDesertEagle");
	}
	else if(hammerweapon==303)
	{
		SetWeapon("AEoDGoldenColts");
	}
	else if(hammerweapon==304)
	{
		SetWeapon("AEoDMac10");
	}
	else if(hammerweapon==305)
	{
		SetWeapon("AEoDPistol");
	}
	else if(hammerweapon==306)
	{
		SetWeapon("AEoDSPASShotgun");
	}
	else if(hammerweapon==307)
	{
		SetWeapon("AEoDMP5");
	}
	else if(hammerweapon==308)
	{
		SetWeapon("AEoDRubinWand");
	}
	else if(hammerweapon==309)
	{
		SetWeapon("AEoDTekBow");
	}
	else if(hammerweapon==310)
	{
		SetWeapon("AEoDFlareGun");
	}
	else if(hammerweapon==311)
	{
		SetWeapon("AEoDCrossbow");
	}
	else if(hammerweapon==312)
	{
		SetWeapon("AEoDElfWand");
	}
	else if(hammerweapon==313)
	{
		SetWeapon("AEoDBeretta");
	}
	else if(hammerweapon==314)
	{
		SetWeapon("AEoDGargoyleWand");
	}
	else if(hammerweapon==315)
	{
		SetWeapon("AEoDRifle");
	}
	else if(hammerweapon==316)
	{
		SetWeapon("AEoDBlaster");
	}
	else if(hammerweapon==317)
	{
		SetWeapon("AEoD357");
	}
	else if(hammerweapon==318)
	{
		SetWeapon("AEoDAssaultShotgun");
	}
	else if(hammerweapon==319)
	{
		SetWeapon("AEoDFiveSevenPistol");
	}
	if(hammerweapon==401)
	{
		SetWeapon("AEoDAWP");
	}
	else if(hammerweapon==402)
	{
		SetWeapon("AEoDCMRifle");
	}
	else if(hammerweapon==403)
	{
		SetWeapon("AEoDCombatShotgun");
	}
	else if(hammerweapon==404)
	{
		SetWeapon("AEoDCrystalGun");
	}
	else if(hammerweapon==405)
	{
		SetWeapon("AEoDDemonOrb");
	}
	else if(hammerweapon==406)
	{
		SetWeapon("AEoDSerpentStaff");
	}
	else if(hammerweapon==407)
	{
		SetWeapon("AEoDBioRifle");
	}
	else if(hammerweapon==408)
	{
		SetWeapon("AEoDDisruptor");
	}
	else if(hammerweapon==409)
	{
		SetWeapon("AEoDRiotGun");
	}
	else if(hammerweapon==410)
	{
		SetWeapon("AEoDShockRifle");
	}
	else if(hammerweapon==411)
	{
		SetWeapon("AEoDDragonClaw");
	}
	else if(hammerweapon==412)
	{
		SetWeapon("AEoDVoodooDoll");
	}
	else if(hammerweapon==413)
	{
		if(CheckInventory("AEoDBloodShotgun"))
		{
			SetWeapon("AEoDBloodShotgun");
		}
		else
		{
			SetWeapon("AEoDBloodShotgun2");
		}
	}
	else if(hammerweapon==414)
	{
		SetWeapon("AEoDBloodShotgun2");
	}
	else if(hammerweapon==415)
	{
		SetWeapon("AEoDDoubleBarreled");
	}
	else if(hammerweapon==416)
	{
		SetWeapon("AEoDSniperRifle");
	}
	else if(hammerweapon==417)
	{
		SetWeapon("AEoDCarbine");
	}
	if(hammerweapon==501)
	{
		SetWeapon("AEoDFlamethrower");
	}
	else if(hammerweapon==502)
	{
		SetWeapon("AEoDFreezethrower");
	}
	else if(hammerweapon==503)
	{
		SetWeapon("AEoDLaserGun");
	}
	else if(hammerweapon==504)
	{
		SetWeapon("AEoDMiniGun");
	}
	else if(hammerweapon==505)
	{
		SetWeapon("AEoDNailGun");
	}
	else if(hammerweapon==506)
	{
		SetWeapon("AEoDPlasmaRifle");
	}
	else if(hammerweapon==507)
	{
		SetWeapon("AEoDWyvernHeart");
	}
	else if(hammerweapon==508)
	{
		SetWeapon("AEoDAssaultRifle");
	}
	else if(hammerweapon==509)
	{
		SetWeapon("AEoDDemonStaff");
	}
	else if(hammerweapon==510)
	{
		SetWeapon("AEoDHyperblaster");
	}
	else if(hammerweapon==511)
	{
		SetWeapon("AEoDNailGunMK2");
	}
	else if(hammerweapon==512)
	{
		SetWeapon("AEoDSkullRod");
	}
	else if(hammerweapon==513)
	{
		SetWeapon("AEoDHornetGun");
	}
	else if(hammerweapon==514)
	{
		SetWeapon("AEoDIceStormRod");
	}
	else if(hammerweapon==515)
	{
		SetWeapon("AEoDGaussGun");
	}
	if(hammerweapon==601)
	{
		SetWeapon("AEoDHowitzer");
	}
	else if(hammerweapon==602)
	{
		SetWeapon("AEoDChickenLauncher");
	}
	else if(hammerweapon==603)
	{
		SetWeapon("AEoDFireStormSpell");
	}
	else if(hammerweapon==604)
	{
		SetWeapon("AEoDGrenadeLauncher");
	}
	else if(hammerweapon==605)
	{
		SetWeapon("AEoDWarAxe");
	}
	else if(hammerweapon==606)
	{
		SetWeapon("AEoDLightningRod");
	}
	else if(hammerweapon==607)
	{
		SetWeapon("AEoDMeteoriteRod");
	}
	else if(hammerweapon==608)
	{
		SetWeapon("AEoDRazor");
	}
	else if(hammerweapon==609)
	{
		SetWeapon("AEoDRocketLauncher");
	}
	else if(hammerweapon==610)
	{
		SetWeapon("AEoDScarabStaff");
	}
	else if(hammerweapon==611)
	{
		SetWeapon("AEoDMissileLauncher");
	}
	else if(hammerweapon==612)
	{
		SetWeapon("AEoDEnlightenmentStaff");
	}
	else if(hammerweapon==613)
	{
		SetWeapon("AEoDPMFLayer");
	}
	if(hammerweapon==701)
	{
		SetWeapon("AEoDLifeLeech");
	}
	else if(hammerweapon==702)
	{
		SetWeapon("AEoDTeslaCannon");
	}
	else if(hammerweapon==703)
	{
		SetWeapon("AEoDDevastator");
	}
	else if(hammerweapon==704)
	{
		SetWeapon("AEoDPerforator");
	}
	else if(hammerweapon==705)
	{
		SetWeapon("AEoDPlutoniumCannon");
	}
	else if(hammerweapon==706)
	{
		SetWeapon("AEoDThunderbolt");
	}
	else if(hammerweapon==707)
	{
		SetWeapon("AEoDVulcanCannon");
	}
	else if(hammerweapon==708)
	{
		SetWeapon("AEoDRipperGun");
	}
	else if(hammerweapon==709)
	{
		SetWeapon("AEoDPrismaCannon");
	}
	else if(hammerweapon==710)
	{
		SetWeapon("AEoDPulseGun");
	}
	else if(hammerweapon==711)
	{
		SetWeapon("AEoDRaptor");
	}
	else if(hammerweapon==712)
	{
		SetWeapon("AEoDIncinerator");
	}
	else if(hammerweapon==713)
	{
		SetWeapon("AEoDGuardianHead");
	}
	else if(hammerweapon==714)
	{
		SetWeapon("AEoDIceWand");
	}
	else if(hammerweapon==715)
	{
		SetWeapon("AEoDArbalest");
	}
	else if(hammerweapon==716)
	{
		SetWeapon("AEoDFragLauncher");
	}
	else if(hammerweapon==717)
	{
		SetWeapon("AEoDConcussionLauncher");
	}
	if(hammerweapon==801)
	{
		SetWeapon("AEoDDSparilStaff");
	}
	else if(hammerweapon==802)
	{
		SetWeapon("AEoDNapalmLauncher");
	}
	else if(hammerweapon==803)
	{
		SetWeapon("AEoDHEGrenadeLauncher");
	}
	else if(hammerweapon==804)
	{
		SetWeapon("AEoDRailgun");
	}
	else if(hammerweapon==805)
	{
		SetWeapon("AEoDMindBlower");
	}
	else if(hammerweapon==806)
	{
		SetWeapon("AEoDIncendiary");
	}
	else if(hammerweapon==807)
	{
		SetWeapon("AEoDDeathRay");
	}
	else if(hammerweapon==808)
	{
		SetWeapon("AEoDFlakCannon");
	}
	else if(hammerweapon==809)
	{
		SetWeapon("AEoDLichStaff");
	}
	else if(hammerweapon==810)
	{
		SetWeapon("AEoDMorserLauncher");
	}
	else if(hammerweapon==811)
	{
		SetWeapon("AEoDPulseCannon");
	}
	else if(hammerweapon==812)
	{
		SetWeapon("AEoDShredderStaff");
	}
	else if(hammerweapon==813)
	{
		SetWeapon("AEoDRavenStaff");
	}
	else if(hammerweapon==814)
	{
		SetWeapon("AEoDIonCannon");
	}
	else if(hammerweapon==815)
	{
		SetWeapon("AEoDPhalanx");
	}
	else if(hammerweapon==816)
	{
		SetWeapon("AEoDTomeOfSet");
	}
	else if(hammerweapon==817)
	{
		SetWeapon("AEoDSniperRailgun");
	}
	if(hammerweapon==901)
	{
		SetWeapon("AEoDSoulReaver");
	}
	else if(hammerweapon==902)
	{
		SetWeapon("AEoDGluonGun");
	}
	else if(hammerweapon==903)
	{
		SetWeapon("AEoDTempestStaff");
	}
	else if(hammerweapon==904)
	{
		SetWeapon("AEoDBloodScourge");
	}
	else if(hammerweapon==905)
	{
		SetWeapon("AEoDHellCore");
	}
	else if(hammerweapon==906)
	{
		SetWeapon("AEoDHERocketLauncher");
	}
	else if(hammerweapon==907)
	{
		SetWeapon("AEoDPrototype");
	}
	else if(hammerweapon==908)
	{
		SetWeapon("AEoDRailgunPrototype");
	}
	else if(hammerweapon==909)
	{
		SetWeapon("AEoDSoulLeech");
	}
	else if(hammerweapon==910)
	{
		SetWeapon("AEoDWraithVerge");
	}
	else if(hammerweapon==911)
	{
		SetWeapon("AEoDCrawler");
	}
	else if(hammerweapon==912)
	{
		SetWeapon("AEoDPhotonCannon");
	}
	else if(hammerweapon==913)
	{
		SetWeapon("AEoDHellRoot");
	}
	else if(hammerweapon==914)
	{
		SetWeapon("AEoDDrakan");
	}
	else if(hammerweapon==915)
	{
		SetWeapon("AEoDProteusDynamo");
	}
	else if(hammerweapon==916)
	{
		SetWeapon("AEoDHandCannon");
	}
	if(hammerweapon==1001)
	{
		SetWeapon("AEoDVolcanoCannon");
	}
	else if(hammerweapon==1002)
	{
		SetWeapon("AEoDApocalypse");
	}
	else if(hammerweapon==1003)
	{
		SetWeapon("AEoDBFG9000");
	}
	else if(hammerweapon==1004)
	{
		SetWeapon("AEoDBioForceGun");
	}
	else if(hammerweapon==1005)
	{
		SetWeapon("AEoDDarkFlameStaff");
	}
	else if(hammerweapon==1006)
	{
		SetWeapon("AEoDNova");
	}
	else if(hammerweapon==1007)
	{
		SetWeapon("AEoDQSG");
	}
	else if(hammerweapon==1008)
	{
		SetWeapon("AEoDDarkMatterGun");
	}
	else if(hammerweapon==1009)
	{
		SetWeapon("AEoDFusionCannon");
	}
	else if(hammerweapon==1010)
	{
		SetWeapon("AEoDInferno");
	}
	else if(hammerweapon==1011)
	{
		SetWeapon("AEoDRedeemer");
	}
	else if(hammerweapon==1012)
	{
		SetWeapon("AEoDHellHeavenHand");
	}
	else if(hammerweapon==1013)
	{
		SetWeapon("AEoDHandOfGod");
	}
	else if(hammerweapon==1014)
	{
		SetWeapon("AEoDDeathsHand");
	}
	hammerweapon=0;
}
